### ISSUE TITLE
Extending code rules with xPath

### ISSUE THREAD

**Issue by daguti** [wenns/sonar-cxx#131]
Hi,

I done some rules using xPath template that provides Sonar. I tested my
xPath queries with  sslr-c-toolkit-1.8.jar toolkit. The problem is that when
I activate my set of rules on a quality profile and launch an analysis with
Sonar Runner on Jenkins it gives me a failure stack but don't give me any
ERROR message. I try to set verbose to true but it didn't give me any extra
information.
The rules are made for C/C++ and I'm using the c++ community plugin. I
didn't sure if this is a problem of the plugin or I'm making a mistake.
My Sonar version is 4.1.2.

First of all, thanks for your attention.

Best regards.

**Comment by guwirth** [comment]
Close this. Please reopen if still a problem.
