### ISSUE TITLE
How many parsing errors are acceptable to get good technical debt results?

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#228]
Using sonar.cxx.includeDirectories and sonar.cxx.forceIncludes in the right way results in less parsing errors.

On the other hand analyzing time is increased because of these additional includes. During performance test I found: Most important part is how many and complex includes exist. For example integration of complex boost slow down things.

In my case resulting technical debt was with and without these includes always the same. So wondering if it would not be better not to add system includes and external libraries?

What is your experience?

**Comment by jmecosta** [comment]
@guwirth seems we all agree parser errors should not produce technical debt. This need to be changed before release
