### ISSUE TITLE
Inconclusive issues from cppcheck not marked

### ISSUE THREAD

**Issue by amaigil2** [wenns/sonar-cxx#247]
The new version 0.9.1 is able to handle cppcheck XML format version 2 output so users may now see inconclusive messages (messages with a higher chance to be a false positive).

It would be nice if their status could be shown in the GUI.

**Comment by amaigil2** [comment]
But the information whether a rule is inconclusive or not will be provided by the rules file!?

**Comment by guwirth** [comment]
http://www.sonarqube.org/sonarqube-4-2-in-screenshots/
Tagging seems to be to tag rules and not violations. My understanding is that there is one rule where the violation could be *inconclusive* or not?

**Comment by amai2012** [comment]
cppcheck messages can bei either always inconclusive or depending on the code. So one needs to parse the single report and cannot detect just by the message id only.
