### ISSUE TITLE
permission denied on reports

### ISSUE THREAD

**Issue by rlucca** [wenns/sonar-cxx#267]
Hi folks,

Is possible put a ERROR log to inform the user that the plugin failed to read the reports because permission issues? I had to lost several hours until discover that my report analysis have been failing to submit because permission issues, not because it was not found! My files were in a directory created by the root user and sonar is running with a normal user. :'(

I'm running the sonar-runner with -X and I didn't see any log relating this. Is possible include this?

Thanks!

**Comment by guwirth** [comment]
Someone an idea how to do this?

**Comment by guwirth** [comment]
Possible solution: http://javarevisited.blogspot.de/2012/01/how-to-file-permission-in-java-with.html

**Comment by wenns** [comment]
This has synergies with #331: while checking the report path for existence, one can also add the check for read permission and discriminate those cases in the warning.
