### ISSUE TITLE
cppcheck report results not loaded as issues in Sonar: how to troubleshoot

### ISSUE THREAD

**Issue by jfallot** [wenns/sonar-cxx#278]
Current env:
. Sonar 4.4
. C++ (Community) plugin version 0.9
. Using sonar-runner to run sonar analysis

My problem: although the cppcheck report result is available and the sonar analysis successful (metrics OK), No issues are showing up in Sonar (although there are a lot...).

Checks done:
. Run sonar-runner with -X: not much useful information is dumped about cxx plugin execution
. Numerous tests on cppcheck report path (absolute, relative)

In a previous env:
. Sonar 4.2
. Maven used to launch Sonar analysis
The issues were correctly reported in Sonar.

My Questions:
How can I more deeply debug the C++ plugin when launching the analysis by sonar-runner?
Attach a remote debugger to Sonar server?
What is the right code branch for 0.9 version of the C++ (Community) plugin?

**Comment by hikoust** [comment]
Hi,

Can you please share the modified CxxReportSensor class file or share Git location ? I am using Cxx scan in Sonar and facing the same issue. I dont have required environment to compile sonar source code.

Thanks,
Kaushik

**Comment by guwirth** [comment]
@jfallot could you test that please with 0.9.3-RC1

**Comment by jmecosta** [comment]
@guwirth -> close -> release -> re-open if does not work
