### ISSUE TITLE
Wiki: document changes introduced by the 0.9.2-release

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#323]
0.9.2-Release will come pretty soon (somewhere around the new year)

This issue is for tracking the necessary documentation changes. Those are:

* 'Changes of the xunit feature' #309 
 * document supported xunit format (schema)
 * document 'filename' tag usage
 * document lookup algorithm

```
// The lookup of the test resource for a test case is performed as follows:
// 1. If the testcase carries a filepath just perform the lookup using this data.
// As we assume this as the absolute knowledge, we dont want to fallback to other
// methods, we want to FAIL.
// 2. Do a lookup using unchanged value of classname. When this failed, fallback to 3.
// 3. Use the classname to search in the lookupTable (this is the AST-based lookup)
// and redo the lookup in Sonar with the gained value.
```

* New C-Compatibility mode
 * No full C-grammar-based parsting, just a compatibility mode consisting of keyword replacement and g++ grammar tuning
 * Configuration properties used

* The force zero coverage - feature

**Comment by wenns** [comment]
This seems to be done
