### ISSUE TITLE
Problem in getting cppCheck checker/rules description through .html files

### ISSUE THREAD

**Issue by rajatbhushan20** [wenns/sonar-cxx#329]
Hi,
I have created .html(files) description for cppCheck rules for sonar-cxx-cxx-0.9.2 plugin
Now to get these .html files read from server as Rules Description I wondered where to put these in plugin. Finally I dumped these .html files at three places 
 a) sonar-cxx-cxx-0.9.2.Beta\cxx-checks\src\main\resources\org\sonar\l10n\cxx\rules\cxx
 b) Created a Directory sonar-cxx-cxx-0.9.2.Beta\cxx-checks\src\main\resources\org\sonar\l10n\cppcheck\rules\cppcheck
 c) Created another directory sonar-cxx-cxx-0.9.2.Beta\sonar-cxx-plugin\src\main\resources\org\sonar\l10n\cppcheck\rules\cppcheck
Then, I rebuild the plugin it successfully build.
I replace the newly generated sonar-cxx-plugin-0.9.2-SNAPSHOT.jar in server and restart the server.

Even after putting these files everywhere,its still not showing those rule description in server.
Please help. Thanks in advance.
Best Regards.

**Comment by wenns** [comment]
This looks to be answered, please reopen if not.
