### ISSUE TITLE
Get rid of default values for the sonar.cxx.<reportsource>.reportPath

### ISSUE THREAD

**Issue by wenns** [wenns/sonar-cxx#331]
I consider those values to be of no real help, introducing them was probably a dumb idea. Also, once we have no default values anymore, we could print warnings into the log if a value is set and yields no files, which is valuable user feedback.

**Comment by guwirth** [comment]
@wenns does this mean only removing the defaults or do we have to add also checks/warnings?

**Comment by wenns** [comment]
I think this task is composed of following smaller ones:
- remove the default paths, and all the code around them
- modify the shouldExecute... to let the sensor run *only if the according report property is set*
- add a warning if the property doesnt point to a file
- adjust the documentation accordingly, mention in the change in the upgrade nodes.

That way, we have (somewhat) smaller logs, a little bit less code, (somewhat) better running times and better usability because of the warnings.

**Comment by wenns** [comment]
By the way: this issue becomes apparent in #278 thread: if the plugin had warned about the report pointing to nothing, analysing the problem for @jfallot would have been a lot easier.
