### ISSUE TITLE
Private methode "matchFile" is not used (LineRegularExpressionCheck.java)

### ISSUE THREAD

**Issue by Bertk** [wenns/sonar-cxx#350]
The Methode "matchFile" is not used and should be removed.

https://github.com/wenns/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/LineRegularExpressionCheck.java

**Comment by guwirth** [comment]
It's a bug I will provide a fix. matchFile must be called.

**Comment by wenns** [comment]
Fixed by #356
