### ISSUE TITLE
Potential resource leak "FileInputStream input" never closed

### ISSUE THREAD

**Issue by Bertk** [wenns/sonar-cxx#351]
I am not sure but saw a warning on this resource leak. Please confirm this is OK.

https://github.com/wenns/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/FileRegularExpressionCheck.java

**Comment by guwirth** [comment]
It's a bug I will provide a fix.

**Comment by wenns** [comment]
Fixed by #355
