### ISSUE TITLE
java.lang.NullPointerException when analyzing an union declared as a class member

### ISSUE THREAD

**Issue by jfallot** [wenns/sonar-cxx#366]
Hello,

I am using the 0.9.2 plugin under development (I forked it on dec 30th: https://github.com/jfallot/sonar-cxx).

The cxx analysis stops with the below exception.

After debugging, it appears that:
* An union member declared in a class is identified as classSpecifier in the AstNode
* The below method generates the NullPointer, since the getFirstDescendant class returns null

```java
private void visitClassSpecifier(AstNode classSpecifier) {

        if (!isPublicApiMember(classSpecifier)) {
            logDebug(classSpecifier
                    .getFirstDescendant(CxxGrammarImpl.className)
                    .getTokenValue()
                    + " not in public API");
            return;
        }
```

I unfortunately cannot share the source samples which cause the issue.
What else can I do to progress in the troubleshooting?

`` java.lang.NullPointerException
	at org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitClassSpecifier(AbstractCxxPublicApiVisitor.java:219)
	at org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitNode(AbstractCxxPublicApiVisitor.java:138)
	at com.sonar.sslr.impl.ast.AstWalker.visitNode(AstWalker.java:114)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:85)
	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
``

**Comment by jfallot** [comment]
Please find below the corresponding code "anonymized" wothout chaging its structure. It should help to reproduce the issue:

``` c++
#ifndef _MYINC_
#define _MYINC_
/*
** $NoKeywords: $
** $Header: $
** <$LegalNotice$>
**
*/

// forward declarations
class AAAaaa;
class AAAbbb;
class AAAccc;
class IIIaaa;
class SSSaaa;

// includes
#include "a/b.hxx"
#include "c/d.hxx"
#include "e/f.hxx"
#include "g/h.hxx"
#include "i/j.hxx"
#include "k/l.hxx"
#include "m/n.hxx"
#include "o/p.hxx"

class AAAddd;
typedef SSSbbb<AAAddd*, 5, SSSccc<AAAddd*, SV_POOL_OTHER> > AAAfff;

class AAAddd
{
	friend class AAAeee;

	friend std::ostream& operator << (std::ostream& out, const AAAddd& poll);

public:

	ALLOCATE(AAAddd)

	enum modeE
	{
		wait  = MODE_WAIT,
		poll  = MODE_POLL,
		guess = MODE_GUESS,
		fail  = MODE_FAIL,
		none  = MODE_PROPAGATE
	};

	AAAddd (AAAeee* piece,
		const AAAeee* replace,
		const IIIddd* stuff,
		const IIIaaa* indicator);

	AAAddd (sid stuff, sid variable)
		: stuff_ (stuff)
	{
		recipe.lll_ = NULL;
		core.variable_ = variable;
		flags.mode_ = none;
	}

	~AAAddd();

	static void initialize();

	static unsigned int hash (const void* x);
	static int rank (const void* x, const void *y);
	IIIbbb* key() const;

	const TTTaaa& delay() const { return delay_; }

	bool operator> (const AAAddd &poll) const;
	bool operator< (const AAAddd &poll) const;
	bool operator== (const AAAddd &poll) const;
	bool operator!= (const AAAddd &poll) const;

	static AAAfff find (sid stuff, sid variable);

	const IIIaaa* indicator() const;

	// signal last poll status
	bool signal (AAAccc* thread,
		PPPaaa* piece,
		const TIMEstamp& timestamp,
		DDDaaa::statusE status,
		AAAbbb** values,
		bool& restartGuessmode);

	// compute poll index
	double index() const;

	// compute poll mode
	unsigned int mode() const;

	// set gone & mode
	unsigned int setGone (unsigned int newGone);
	void setMode (AAAddd::modeE mode, bool force = FALSE);

	uint32 ping() const { return ping_; }
	uint32 pong() const { return pong_; }

	sid stuff() const { return stuff_; }

	SSSaaa* do() const;
	void do (SSSaaa* svar);

	void getChildren( SSSggg<const IIIccc* >& choices ) const;

	AAAggg* getChoice (sid id);

	void restartGuess();

	static AAAddd* findBySlot(const AAAeee *piece);
	static void setSlot(const AAAeee* piece, AAAddd* pslot);

private:

	AAAddd (const AAAddd&) { relASSERT (0); }
	AAAddd& operator = (const AAAddd&) { relASSERT (0); return *this; }

	AAAeee* slot_;

	sid stuff_;

	union
	{
		sid variable_;					
		PPPaaa* poll_;					
		AAAhhh* list_;				
	} core;

	struct
	{
		unsigned int mode_     :3;	
		unsigned int multiFI_  :1;	
		unsigned int default_  :1;	
		unsigned int multiF_   :1;	
		unsigned int           :2;
		unsigned int index_    :24;	
	} flags;

	unsigned int ping_;
	unsigned int pong_;
	unsigned int gone_;
	unsigned int default_;	

	TTTaaa delay_;

	union
	{
		AAAaaa* lll_;
		// TODO
		SSSaaa* sss_;
	} recipe;

	static unsigned int limit_;


	static SSSddd<IIIbbb, AAAddd*> wait_;

	// Dictionary to hold AAAeee -> AAAddd link
	static SSSeee dicLock_;
	static SSSfff<sid, AAAddd*, SV_POOL_LONGTERM, SV_POOL_APPLICATION_CNTL> dic_;
	static unsigned int hash (const sid& id) { return id; }

	bool getIt (AAAhhh* list,
		AAAbbb** values,
		size_t index,
		bool stack);

	bool checkIt (AAAggg* choice,
		const DDDaaa::statusE status,
		const AAAbbb* values);

	void guessit (const AAAeee* replace,
		const IIIddd* stuff = NULL,
		const IIIaaa* indicator = NULL);

	bool checkLastChoice (AAAbbb* values);

#ifdef LDEBUG
	bool debug() const;
#endif
};


// compute poll mode
inline unsigned int AAAddd::mode() const
{
	return flags.mode_ != wait && gone_ > 0 ? fail : flags.mode_;
}

// get childs collection for information system encoding
inline void AAAddd::getChildren( SSSggg<const IIIccc* >& choices ) const
{
	for ( unsigned int i = 0; i < core.list_->entries (); i++ )
		choices.insert( core.list_->at(i) );
}

inline SSSaaa* AAAddd::do() const
{
	dbgASSERT (flags.mode_ == wait);
	return (recipe.sss_ != NULL ? recipe.sss_ : NULL);
}

inline void AAAddd::do (SSSaaa* svar)
{
	// TODO 
}

std::ostream& operator << (std::ostream& out, AAAddd::modeE mode);
std::ostream& operator << (std::ostream& out, const AAAddd& poll);

#endif /* Include protection */

```

**Comment by wenns** [comment]
Thank you, it's much appreciated. @typz: are you looking into the issue or should I?

**Comment by lcintrat** [comment]
I will have a look this evening

**Comment by wenns** [comment]
Ahem. Yes, sorry, I thought typz was the author ;)

**Comment by jfallot** [comment]
I encounter a very similar issue on a different test case:
Use the jvmdi.h include that was shipped with the JDK (by example: https://www.mayrhofer.eu.org/downloads/projects/contextprediction/doc/jvmdi_8h-source.html), the issue happens when analyzing line 532:

```
 java.lang.NullPointerException
	at org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitClassSpecifier(AbstractCxxPublicApiVisitor.java:233)
	at org.sonar.cxx.visitors.AbstractCxxPublicApiVisitor.visitNode(AbstractCxxPublicApiVisitor.java:138)

```

**Comment by wenns** [comment]
Good! Can we back the fix(es) with tests, to prevent regressions?

**Comment by lcintrat** [comment]
@jfallot thank you for the file.

Note that line 104, the C++ <code>do</code> reserved keyword is used as a function name (maybe an issue of the obsfuscator ?). This triggers a syntax error and I guess that the recovery skip the next <code>private</code>, leading to false positives (according to the traces, the next <code>AAAddd</code> constructor is considerer as public API).

However, no NPE shall be thrown... still working on it

**Comment by lcintrat** [comment]
Root cause is identified: bad support of unnamed struct. Fixing it.
I will check if the same issue may happen with classes.
