### ISSUE TITLE
Boost Unit Test, xunit.provideDetails=true, filename tag

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#372]
Does someone know how to create boost unit test xml reports with file information?

**Comment by jmecosta** [comment]
Windows? I've created a msbuild task that runs gtest and converts reports.
Not sure if there something similar out there for boost

**Comment by guwirth** [comment]
Yes Windows. I'm interested in the boost options to create test-suite or test-case tags with a file attribute.

**Comment by jmecosta** [comment]
this is the task ive created:
https://github.com/jmecosta/MSBuild-SonarQube-CXX/blob/master/GtestXunitConverterTask/GtestXunitConverterTask.fs

and its used like this:
https://github.com/jmecosta/sonar-cxx/blob/bdd/bullseye-and-custom-rules/integration-tests/testdata/googletest_bullseye_vs_project/PathHandling.Test/PathHandling.Test.vcxproj

just not sure how much work you will require to adapt it to boost... sorry

**Comment by guwirth** [comment]
Did some tests, see my results below. Did also an update in the wiki. Also this needs a new XSL.

Example:
```C++
#define BOOST_TEST_MODULE my_module
#include <boost/test/unit_test.hpp>

int add(int i, int j) { return i + j; }

BOOST_AUTO_TEST_SUITE(my_test_suite)

BOOST_AUTO_TEST_CASE(my_test)
{
	// seven ways to detect and report the same error:
	BOOST_CHECK(add(2, 2) == 4);         // #1 continues on error

	BOOST_REQUIRE(add(2, 2) == 4);       // #2 throws on error

	if (add(2, 2) != 4)
		BOOST_ERROR("Ouch...");          // #3 continues on error

	if (add(2, 2) != 4)
		BOOST_FAIL("Ouch...");           // #4 throws on error

	if (add(2, 2) != 4) throw "Ouch..."; // #5 throws on error

	BOOST_CHECK_MESSAGE(add(2, 2) == 4,  // #6 continues on error
		"add(..) result: " << add(2, 2));

	BOOST_CHECK_EQUAL(add(2, 2), 4);	 // #7 continues on error
}

BOOST_AUTO_TEST_SUITE_END()
```
Preferred command line execution to get all information (```--log_level=all``` or ```--log_level=success```):
```BASH
<test executable> --log_format=XML --log_sink=<filename> --log_level=all --report_level=no
```
Resulting Unit Test XML report:
```XML
<TestLog>
  <TestSuite name="my_module">
    <TestSuite name="my_test_suite">
      <TestCase name="my_test">
        <Info file="d:/test/example.cpp" line="11"><![CDATA[check add(2, 2) == 4 passed]]></Info>
        <Info file="d:/test/example.cpp" line="13"><![CDATA[check add(2, 2) == 4 passed]]></Info>
        <Info file="d:/test/example.cpp" line="23"><![CDATA[check 'add(..) result: 4' passed]]></Info>
        <Info file="d:/test/example.cpp" line="26"><![CDATA[check add(2, 2) == 4 passed]]></Info>
        <TestingTime>1000</TestingTime>
      </TestCase>
    </TestSuite>
  </TestSuite>
</TestLog>
```
Alternative command line to get only test suite information (```--log_level=test_suite```):
```BASH
<test executable> --log_format=XML --log_sink=<filename> --log_level=test_suite --report_level=no
```
Resulting Unit Test XML report:
```XML
<TestLog>
  <TestSuite name="my_module">
    <TestSuite name="my_test_suite">
      <TestCase name="my_test">
        <TestingTime>1000</TestingTime>
      </TestCase>
    </TestSuite>
  </TestSuite>
</TestLog>
```

**Comment by guwirth** [comment]
not supported with V0.9.2, also new stylesheet needed
