### ISSUE TITLE
Support Vera++ native xml report

### ISSUE THREAD

**Issue by benispeti** [wenns/sonar-cxx#382]
Plugin supports xml report generated by 'vera++Report2checkstyleReport.perl' script, but it does not support xml file generated by vera++ itself.

XML generation using vera++ version 1.2.1:
vera++ --xml-report vera-report.xml main.cxx

**Comment by guwirth** [comment]
Could you provide an example please.

**Comment by benispeti** [comment]
Sure. I tested with the following simple main.cxx file:
```
int main(int argc, char **argv) {
}
```

First I describe how I could attach vera++ report to sonar report:
1. Generated simple vera report into **vera.out** file
```
vera++ -s -o vera.out main.cxx
```
The content of vera.out file:
```
main.cxx:1: T013: no copyright notice found
main.cxx:2: T011: closing curly bracket not in the same line or column
```
2. Convert vera.out plain text report to xml using [your script](https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/tools/vera%2B%2BReport2checkstyleReport.perl)
```
vera++Report2checkstyleReport.perl < vera.out > vera.xml
```
The content of vera.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="5.0">
	<file name="main.cxx">
		<error line="1" severity="warning" message=" no copyright notice found" source="T013"/>
		<error line="2" severity="warning" message=" closing curly bracket not in the same line or column" source="T011"/>
	</file>
</checkstyle>
```

Sonar plugin can parse this xml report, but the xml generated directly from vera++ is not parseable by the plugin.

1. Using the same main.cxx I generated xml report directly from vera++ (version 1.2.1)
```
vera++ -s -x vera2.xml main.cxx
```
The content of vera2.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<vera>
    <file name="main.cxx">
        <report rule="T013" line="1">![CDATA[no copyright notice found]]</report>
        <report rule="T011" line="2">![CDATA[closing curly bracket not in the same line or column]]</report>
    </file>
</vera>
```

So it looks the two xml files has different tag names and structure, and that's why the second xml report cannot be parsed by sonar plugin.

**Comment by guwirth** [comment]
@wenns how was this originally intended?

**Comment by wenns** [comment]
This code predates my maintainership. I dont know.

**Comment by guwirth** [comment]
@benispeti ```-x``` option to create directly XML seems to be 'new':
* could you please find out when this was introduced?
* is there a schema in the documentation of the Vera++ tool you can provide?

**Comment by guwirth** [comment]
Found this: https://bitbucket.org/verateam/vera/wiki/Running
* ```-x --xml-report filename``` writes the XML report to this file. Not used by default. A single dash - means that the standard output or the error output will be used, depending on the usage of the --warning or --error option. This option may be used several times in order to produce the reports in several locations - for example on the standard output and in a file. This report is not produced by default.
* ```-c --checkstyle-report filename``` writes the checkstyle report to this file. Not used by default. A single dash - means that the standard output or the error output will be used, depending on the usage of the --warning or --error option. This option may be used several times in order to produce the reports in several locations - for example on the standard output and in a file. This report is not produced by default.

and this: https://bitbucket.org/verateam/vera/issue/5/native-checkstyle-xml-output

**Comment by benispeti** [comment]
@guwirth my guess was also that this is a quite new feature in vera++. Actually I'm just a user of vera, so I do not know if there is a schema for their xml or not.

**Comment by wenns** [comment]
So using
```
-c --checkstyle-report filename
```
you can produce checkstyle-style report directly, and not via the perl script?

**Comment by benispeti** [comment]
The perl script was working fine for me for the standard output, but I did not try the checkstyle report generation (-c) before. Now I'm checking that option of vera and it seems to be what I was looking for. For the same example file I generated the checkstyle report:
```
vera++ -s -c vera3.xml main.cxx
```
I got this output:
```
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="5.0">
    <file name="main.cxx">
        <error source="T013" severity="info" line="1" message="no copyright notice found" />
        <error source="T011" severity="info" line="2" message="closing curly bracket not in the same line or column" />
    </file>
</checkstyle>
```
The only difference between the report generated by the perl script and vera's checkstyle report is the severity of the found problems. Anyway this output seems to be working fine for me. Thanks!

**Comment by guwirth** [comment]
So do we need native Vera++ support anymore or should we close this issue?

**Comment by jmecosta** [comment]
1.3.0 just release 
https://bitbucket.org/verateam/vera/wiki/Home

**Comment by guwirth** [comment]
Question was not if we need Vera++ support. Question was if we have to support both options: ```-x --xml-report filename``` and ```-c --checkstyle-report filename```.

**Comment by wenns** [comment]
We can process the reports created with '-c', so all is fine... If someone want to feed an vera++ report into  SQ, all it takes is to switch the reporting option, if necessary.

**Comment by guwirth** [comment]
Ok let's update docu and close it then.

**Comment by jmecosta** [comment]
I be just verified version 1.3 and -c is still supported so nothing need

**Comment by benispeti** [comment]
It is fine for me to simply close this issue. Thanks again!

**Comment by guwirth** [comment]
documented: https://github.com/wenns/sonar-cxx/wiki/Code-checkers

**Comment by yujie123jw** [comment]
I also appeared the same mistake but it was a little different, it just appeared in the report - > click on the problem.
for example: issuekey  this page is no good.
/issues/search#issues=42bdd3d4-2f44-4e46-9a4d-0ae6e2c4157e
<?xml version="1.0" encoding="UTF-8"?>

<vera>

    <file name="src/HelloWorld.cpp">
        <report line="1">![CDATA[no copyright notice found]]</report>
        <report line="16">![CDATA[trailing empty line(s)]]</report>
    </file>

    <file name="src/RandDemo.cc">

        <report line="1">![CDATA[no copyright notice found]]</report>
        <report line="18">![CDATA[semicolon is isolated from other tokens]]</report>
        <report line="19">![CDATA[semicolon is isolated from other tokens]]</report>
        <report line="25">![CDATA[keyword 'while' not followed by a single space]]</report>
        <report line="30">![CDATA[trailing whitespace]]</report>
        <report line="31">![CDATA[trailing whitespace]]</report>
....................................

i think 
Connected to the following is the correct display. 
Or say that it should be connected to this page:
/issues/search#issues=3f19c880-5989-4c4c-9ebd-6115a72cb83a






 C++::Simple Project::SonarQube Runner
 src/HelloWorld.cpp

#include <iostream>

no copyright notice found

5min debt
	 No tags

using namespace std;
// https://www.baidu.com/more/
int main ()
{
int I;
   cout << "Hello World!";
   return 0;
I++;
I++;
}

if (x) foo();     // bad style
if (x) { foo(); } // OK
..................

Only Vera+ appear this problem, not cppcheck!

**Comment by yujie123jw** [comment]
Very much regret! I can't page HTML because, the GitHub no support.
![Uploading one.jpg…]()

![two](https://cloud.githubusercontent.com/assets/13860761/9780810/0b74c264-57c0-11e5-897c-3482b0bee85e.jpg)

**Comment by jmecosta** [comment]
Hi, 

Can't you just use the -c option in vera and drop the script?

**Comment by guwirth** [comment]
Similar issue?
https://github.com/wenns/sonar-cxx/issues/382

**Comment by yujie123jw** [comment]
I just use VERA++ 1.21, This is a very interesting question.
I'm descovered the following:
this is display OK!
find ./src -regex ".*\.cc"|vera - -showrules -nodup|& ./verareport.pl>vera-result-1.xml
find ./src -regex ".*\.cpp"|vera - -showrules -nodup|& ./verareport.pl>vera-result-2.xml

this is display WRONG!
find ./src -regex ".*\.cpp\|.*\.h\|.*\.c\|.*\.cxx\|.*\.cc"|vera - -showrules -nodup|& ./verareport.pl>vera-result-1.xml

**Comment by yujie123jw** [comment]
This page has eaten me a few　""\"".
like this!!
 find ./src -regex ".*\\\.cpp\|.*\\\.h"|vera - -showrules -nodup|& ./verareport.pl>vera-result-1.xml

**Comment by yujie123jw** [comment]
After the first time to use VERA++ 1.21, I found that to separately use the 2 orders is ok 
(find ./src -regex ".\*\\\.cc"|vera - -showrules -nodup|& ./verareport.pl>vera-result-1.xml; 
find ./src -regex ".\*\\\.cpp"|vera - -showrules -nodup|& ./verareport.pl>vera-result-2.xml), but if combine the 2 orders (find ./src -regex ".\*\\\.cpp\\\|.\*\\\.h\\\|.\*\\\.c\\\|.\*\\\.cxx\\\|.\*\\\.cc"|vera - -showrules -nodup|& ./verareport.pl>vera-result-1.xml), it will not work.
Is it normal?

**Comment by yujie123jw** [comment]
hi , i have modified my question.
