### ISSUE TITLE
Milestone V0.9.3

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#384]
Hello together,

there is already a new V0.9.3 milestone.
* What are the topics should be next?
* When should be next release?

Current settings:
* **Bugs:** http://github.com/wenns/sonar-cxx/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22M+0.9.3%22+label%3Abug
* **Enhancements:** https://github.com/wenns/sonar-cxx/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22M+0.9.3%22+label%3Aenhancement

Regards,

**Comment by guwirth** [comment]
Remove milestone 0.9.3 from all issues with tag *discussion* and *waiting for answer*.

**Comment by guwirth** [comment]
Any ideas what should be in next release?
What is the main goal? Full SQ 4.5.1 compatibility or partly SQ 5 compatible?
Which features must be in 0.9.3?

**Comment by jmecosta** [comment]
We might need to release a compatibility version to support 5.0 people are
asking about it..

**Comment by guwirth** [comment]
Wondering if SQ 4.5 and SQ 5 support in one version is possible? Are there any API changes in SQ 5 which are not backward compatible?

**Comment by jmecosta** [comment]
4.5.1 is supported by 0.9.2... we only need a new for SQ 5.... What is the
issues with 4.5.1 (why do we need a new release), we can tackle all those
for 5.0?

**Comment by guwirth** [comment]
As far as I understood from @wenns 0.9.2 is still using SQ 4.2 API only?

**Comment by jmecosta** [comment]
We are using 4.5.1 for some time now. No issues here

**Comment by wenns** [comment]
> As far as I understood from @wenns 0.9.2 is still using SQ 4.2 API only?

Yeah... Which doesnt mean it works with 4.5.1 servers just fine ;)

**Comment by guwirth** [comment]
Strategy is still open for me:
1. Update first completely to 4.5.1 API and continue then (maybe do also another SQ 4.5 release)
2. Jump over 4.5.1 and continue with 5.x API (next release is for SQ 5.x) ?

**Comment by jmecosta** [comment]
IMO we should skip. 4.5.1 is usable with the current version. 5.0 is not.

**Comment by guwirth** [comment]
There are still some bigger bugs in 0.9.2:
- missing C++11 compliance
- preprocessor limitations
- missing boost test framework support
- ...
4.5 is a LTS version which must be supported, so I tend to finish first this before jumping to 5.x. Have anyway still the feeling that this non LTS versions are always far away form being stable.

**Comment by guwirth** [comment]
Hi together,

**I need your help.** There is a first version with 4.5.2 API available. Please test it and give feedback.

It is planned to release the cxx 0.9.3 plugin version for SQ 4.5.(2+) LTS by end of the month (2015-04-30). In case you like to add features please:
* rebase your code in the pull requests
* remove deprecated APIs

Minimal goal is to close at least all known open bugs.

Thanks guwirth

**Comment by jmecosta** [comment]
ive done 2 of my pull request. the reactor pr can be moved to a new millestone if there is not time now... also am happy on using a non module approach that works well with the current plugin. so if decide not to support those we can drop that pr

i will update my instance once i can get the buildlog approach merged into master. has i am using that currently and i need it

**Comment by guwirth** [comment]
Proposed timeline for 0.9.3
* open for extensions by 2015-04-19
* after 2015-04-19 only testing and stabilization
* release 2015-04-30

**Comment by jmecosta** [comment]
i think am ready with my changes

**Comment by ttoleung** [comment]
It is worth to note the latest version is 4.5.4, shall we make it compatible with 4.5.4 ? (I believe API is unchanged, so should be no additional work).

**Comment by jmecosta** [comment]
I think so

**Comment by guwirth** [comment]
Yes we should test at least with latest SQ LTS version (4.5.4) and latest available SQ version (5.1).

**Comment by guwirth** [comment]
Hi all,

Have sometimes problems to merge. Would be nice if you always could rebase and squash (combine multiple commits into one) your PR.

Makes it easier for me to merge.
Thx.

**Comment by guwirth** [comment]
clean up of Milestone V0.9.3:
- #358 seems to be the last feature in this release?
- 5 bugs open: #460, #445, #441, #426, #381

reminder:
- open for extensions by 2015-04-19
- after 2015-04-19 only testing and stabilization
- release 2015-04-30

**Comment by jmecosta** [comment]
Try to fix the test this weekend
