### ISSUE TITLE
Almost endless "Updating semaphore Batch", analysis eventually fails

### ISSUE THREAD

**Issue by kgiloo** [wenns/sonar-cxx#389]
sonar cxx analysis seem to have no end, failed after nearly 48 hours (Sensor CxxSquidSensor done: 169751589 ms...)
What is the best procedure to detect what is really wrong? Output does not tell me much...
Code instrumented is ~2.8 million of lines. I had no problem till end of december but suddenly i cannot instrumentate with cxx anymore.
SonarQube 4.5.2, sonar runner 2.4, no UT execution, cxx 0.9.2 (included fix for https://github.com/wenns/sonar-cxx/issues/294)

here the end output:

[exec] 01:42:37.068 INFO  - Directory: 'AAA/BBBB/CCC/src' 
Cycles:0 Feedback cycles:0 Tangles:0 Weight:10.0
     [exec] 01:42:40.589 DEBUG - Updating semaphore batch-my:autoform_r6
	 ............................ Updating semaphore batch-my:autoform_r6
	   [exec] 23:59:53.610 DEBUG - Updating semaphore batch-my:autoform_r6
	..............................
[exec] 15:53:35.828 DEBUG - Updating semaphore batch-my:autoform_r6
     [exec] 15:53:45.831 DEBUG - Updating semaphore batch-my:autoform_r6
     [exec] 15:53:50.373 INFO  - Project 'my:autoform_r6' Cycles:484 Feedback cycles:196 Tangles:961 Weight:66257.0
     [exec] 15:53:51.274 INFO  - Sensor CxxSquidSensor done: 169751589 ms
     [exec] 15:53:51.283 ERROR - JDBC commit failed
     [exec] com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during commit(). Transaction resolution unknown.
     [exec] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_55]	
	 [exec] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_55]
     [exec] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_55]
     [exec] 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.7.0_55]
     [exec] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.27.jar:na]
     [exec] 	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.27.jar:na]
     [exec] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.27.jar:na]
     [exec] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989) ~[mysql-connector-java-5.1.27.jar:na]
     [exec] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975) ~[mysql-connector-java-5.1.27.jar:na]
     [exec] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920) ~[mysql-connector-java-5.1.27.jar:na]
     [exec] 	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1748) ~[mysql-connector-java-5.1.27.jar:na]
     [exec] 	at org.apache.commons.dbcp.DelegatingConnection.commit(DelegatingConnection.java:334) ~[sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.commit(PoolingDataSource.java:211) ~[sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.hibernate.transaction.JDBCTransaction.commitAndResetAutoCommit(JDBCTransaction.java:170) ~[sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:146) ~[sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:54) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.jpa.session.JpaDatabaseSession.commit(JpaDatabaseSession.java:83) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.jpa.session.JpaDatabaseSession.commitAndClose(JpaDatabaseSession.java:69) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:68) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:119) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:194) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:233) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:228) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:221) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] ERROR: Error during Sonar runner execution
     [exec] org.sonar.runner.impl.RunnerException: Unable to execute Sonar
     [exec] 	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:64) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
     [exec] 	at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:51) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:125) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
     [exec] 	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
     [exec] 	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
     [exec] 	at org.sonar.runner.api.Runner.execute(Runner.java:100)
     [exec] 	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.runner.Main.executeTask(Main.java:70)
     [exec] 	at org.sonar.runner.Main.execute(Main.java:59)
     [exec] 	at org.sonar.runner.Main.main(Main.java:53)
     [exec] 	at org.sonar.batch.bootstrap.BootstrapContainer.executeTask(BootstrapContainer.java:173) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] Caused by: javax.persistence.RollbackException: Error while commiting the transaction
     [exec] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:71)
     [exec] 	at org.sonar.jpa.session.JpaDatabaseSession.commit(JpaDatabaseSession.java:83)
     [exec] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67) [sonar-batch-maven-compat-4.5.2.jar:na]
     [exec] 	at org.sonar.jpa.session.JpaDatabaseSession.commitAndClose(JpaDatabaseSession.java:69)
     [exec] 	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48) [sonar-runner-batch8461566086581221244.jar:na]
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_55]
     [exec] 	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
     [exec] 	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:119)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_55]
     [exec] 	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:194)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_55]
     [exec] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_55]
     [exec] 	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93)
     [exec] 	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78)
     [exec] 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87) [sonar-runner-dist-2.4.jar:na]
     [exec] 	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75) [sonar-runner-dist-2.4.jar:na]
     [exec] 	at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_55]
     [exec] 	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:233)	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69) [sonar-runner-dist-2.4.jar:na]
     [exec] 	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50) [sonar-runner-dist-2.4.jar:na]
     [exec] 
     [exec] 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102) [sonar-runner-dist-2.4.jar:na]
     [exec] 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:228)
     [exec] 	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:221)
     [exec] 	at org.sonar.runner.api.Runner.execute(Runner.java:100) [sonar-runner-dist-2.4.jar:na]
     [exec] 	at org.sonar.runner.Main.executeTask(Main.java:70) [sonar-runner-dist-2.4.jar:na]
     [exec] 	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93)
     [exec] 	at org.sonar.runner.Main.execute(Main.java:59) [sonar-runner-dist-2.4.jar:na]
     [exec] 	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78)
     [exec] 	at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:64)
     [exec] 	at org.sonar.runner.Main.main(Main.java:53) [sonar-runner-dist-2.4.jar:na]
     [exec] 15:53:51.366 WARN  - SQL Error: 0, SQLState: null
     [exec] 15:53:51.366 ERROR - Already closed.
     [exec] 	at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:51)
     [exec] 	at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:125)
     [exec] 15:53:51.368 DEBUG - Release semaphore on project : org.sonar.api.resources.Project@204f2ff1[id=20202,key=my:autoform_r6,qualifier=TRK], with key batch-my:autoform_r6
     [exec] INFO: ------------------------------------------------------------------------
     [exec] INFO: EXECUTION FAILURE
     [exec] 	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93)
     [exec] INFO: ------------------------------------------------------------------------
     [exec] Total time: 47:14:01.253s
     [exec] Final Memory: 7M/661M
     [exec] 	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78)
     [exec] 	at org.sonar.batch.bootstrap.BootstrapContainer.executeTask(BootstrapContainer.java:173)
     [exec] INFO: ------------------------------------------------------------------------
     [exec] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
     [exec] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
     [exec] 	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     [exec] 	at java.lang.reflect.Method.invoke(Unknown Source)
     [exec] 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
     [exec] 	... 9 more
     [exec] Caused by: org.hibernate.exception.GenericJDBCException: Cannot release connection
     [exec] 	at org.hibernate.exception.SQLStateConverter.handledNonSpecificException(SQLStateConverter.java:126)
     [exec] 	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:114)
     [exec] 	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
     [exec] 	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:52)
     [exec] 	at org.hibernate.jdbc.ConnectionManager.closeConnection(ConnectionManager.java:478)
     [exec] 	at org.hibernate.jdbc.ConnectionManager.aggressiveRelease(ConnectionManager.java:429)
     [exec] 	at org.hibernate.jdbc.ConnectionManager.afterTransaction(ConnectionManager.java:316)
     [exec] 	at org.hibernate.jdbc.JDBCContext.afterTransactionCompletion(JDBCContext.java:248)
     [exec] 	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:158)
     [exec] 	at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:54)
     [exec] 	... 35 more
     [exec] Caused by: java.sql.SQLException: Already closed.
     [exec] 	at org.apache.commons.dbcp.PoolableConnection.close(PoolableConnection.java:114)
     [exec] 	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.close(PoolingDataSource.java:191)
     [exec] 	at org.hibernate.connection.DatasourceConnectionProvider.closeConnection(DatasourceConnectionProvider.java:97)
     [exec] 	at org.hibernate.jdbc.ConnectionManager.closeConnection(ConnectionManager.java:474)
     [exec] 	... 40 more
sonar:  duration 2834 minutes 2 seconds

**Comment by guwirth** [comment]
Could you provide your configuration settings please?
Which versions of SonarQube, sonar-runner and cxx plugin are you using?
Have you already tried with less includes?
```ini
sonar.cxx.includeDirectories=.
sonar.cxx.errorRecoveryEnabled=true
```

**Comment by kgiloo** [comment]
SonarQube: 4.5.2
SonarRunner: 2.4
cxx plugin (snapshot from 2015-01-12, 0.9.2 incl. https://github.com/wenns/sonar-cxx/issues/294)
...
```javascript
sonar.sources=.
sonar.exclusions=FFF/GG/**a
sonar.language=c++
sonar.sourceEncoding=UTF-8
sonar.jdbc.url=jdbc:mysql://localhost:3306/sonar?useUnicode=true&amp;characterEncoding=utf8
sonar.cxx.includeDirectories=.
sonar.cxx.errorRecoveryEnabled=True

sonar.cxx.cppcheck.reportPath=cppcheck_R6_95908_sonar.xml
sonar.cxx.cppcheck.execPath=C:\PROGRA~2\Cppcheck\CPPCHECK.EXE
sonar.cxx.cppcheck.checks=all
sonar.cxx.cppchecks=all
sonar.cxx.cppcheck.xmlversion=2
```
included only root "." indeed.

**Comment by guwirth** [comment]
Another question: Is the SonarQube Server analysis and database all on one machine? We also have problems if analysis (sonar-runner) and SonarQube Server are on different machines with slow Ethernet connection.

**Comment by lcintrat** [comment]
I had this problem on Sunday, using the evaluation version of SonarQube with embedded database. (I use part of boost for testing). This issue happened when I updated the plugin from 0.9.1 to 0.9.2.
I removed all the database files, and the issue vanished.

Hope this can help...

**Comment by kgiloo** [comment]
SonarQube and MySQL (5.6) are on the same computer (but it is a VM)
Below the overview of involved files on the DB. Can size be part of the trouble? 

![mysql_data_sonar](https://cloud.githubusercontent.com/assets/9213451/5813539/8a0e8310-a07f-11e4-8666-511d0a1b5242.png)

However as CxxSquidSensor is done after almost 48 hours, is it a problem related to instrumentation by cxx or connection/update problem to DB? Would it be worth trying on a fresh/empty DB?

**Comment by guwirth** [comment]
Is the sonar-runner also on the  same machine? Maybe you can check with a ping the latency. During analysis there are plenty of network calls. This will be changed with SQ 5.

**Comment by kgiloo** [comment]
sonar-runner is on the same machine indeed. Thank you for the support, however  i am still looking for an answer to my original question: what could be the root of the problem?  Why is CxxSquidSensor finished after 48 hours, is it analysis related or DB related?

**Comment by guwirth** [comment]
Look at #118 at the end. Gives you a rough feeling for performance numbers.

**Comment by guwirth** [comment]
Close this. Please reopen if this is still an issue.
