### ISSUE TITLE
tabcheck should report issue against each line instead of file

### ISSUE THREAD

**Issue by jmecosta** [wenns/sonar-cxx#390]
- vera works this way
- more often than not more than one person is to be able

**Comment by guwirth** [comment]
Agree we should change this.Should use createLineViolation

class TabCharacterCheck: https://github.com/wenns/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/TabCharacterCheck.java

(With 0.9.2 you can already use LineRegularExpressionCheck  instead.)

**Comment by Bertk** [comment]
I am not sure and one issue per file is sufficient for my purpose. 
- every modern IDE has a format source feature which eliminates the tabs with one click
- one issue can be used to express the techn. debt per file. I use typically 5 minutes for this.

Our legacy code has many occurrences of this finding and the analysis takes much more time if the issue is added per line to the DB. I feel it is better to focus on critical issues and good analysis performance ;-)

**Comment by jmecosta** [comment]
my issue with this, is that looking at the source code in the web ui it does not tell me where the tabs are, so i cannot say which developer has incorrect settings. i will need to get to code and search for the file, open the file to locate where the tab is. after that do a git blame to see who introduce the tab and finally assign to him so that he can fix its VS studio settings. 

to much work imo, so having the issue per line is more beneficial in this case.

**Comment by guwirth** [comment]
What's about an option: per file / per line?

**Comment by jmecosta** [comment]
Sounds good. First to make pull request chooses the default?

**Comment by Bertk** [comment]
A configuration item is OK and the tab issue per line can be added on demand. We do not use the SCM plugin in CI because this extends the cycle time and therefore we cannot see the developer created the issue.

**Comment by guwirth** [comment]
Example for creating line violations:
https://github.com/SonarCommunity/sonar-javascript/blob/master/javascript-checks/src/main/java/org/sonar/javascript/checks/TabCharacterCheck.java

**Comment by guwirth** [comment]
I will provide a solution.

**Comment by jmecosta** [comment]
solution here
https://github.com/SonarCommunity/sonar-xml/blob/master/sonar-xml-plugin/src/main/java/org/sonar/plugins/xml/checks/IllegalTabCheck.java

**Comment by jmecosta** [comment]
nevermind
