### ISSUE TITLE
Multi-Module Project : WARN  - Unable to find resource

### ISSUE THREAD

**Issue by yolani** [wenns/sonar-cxx#391]
Hi there,

i have a little problem analyzing a multi module project and i hope you can help me with it.

I am running Sonar 4.5.2 with the c++ plugin 0.9.4.

i have a project structre like this:

E:\TEMP\TEMP\TEST_PROJECT
├───inc
├───mod1 (contains a source file that includes a header from "inc")
├───mod2 (contains a source file that includes a header from "inc")

My sonar-project.properties looks like this:

sonar.projectKey=Multi
sonar.projectName=Multi
sonar.projectVersion=1

sonar.modules=mod1,mod2

mod1.sonar.projectName=Module1
mod1.sonar.projectBaseDir=mod1
mod1.sonar.sources=.
mod1.sonar.cxx.includeDirectories=../inc

mod2.sonar.projectName=Module2
mod2.sonar.projectBaseDir=mod2
mod2.sonar.sources=.
mod2.sonar.cxx.includeDirectories=../inc

When i run the analysis, i get the following warning and he does not seem to recognise the headers in the "inc" directory:

17:20:29.762 WARN  - Unable to find resource 'E:\temp\temp\test_project\inc\mod2.h' to create a dependency with 'mod2.c'

Can anybody tell me what i'm doing wrong? this worked fine with the old plugin 0.9.3 and sonar 3.x.

thanks in advance,

christian

**Comment by jmecosta** [comment]
just to confirm you are talking about version 0.9.2? can you use absolute paths for this?

**Comment by yolani** [comment]
Sorry, of course i mean version 0.9.2

**Comment by jmecosta** [comment]
we have a few issues with multimodule... the proper support for this was not completed for this version. still a bit under work. you can find a discussion about this in #358 i will try if with that branch your use case is covered

**Comment by yolani** [comment]
Okay, thanks for your answer. so i will create a project config without different modules until this is fixed.

I just toyed around around a little bit with the config, and tried to merge source files from different folders into one module:

sonar.projectKey=Multi
sonar.projectName=Multi
sonar.projectVersion=1

sonar.modules=mod1,mod2

sonar.cxx.includeDirectories=e:\\temp\\temp\\test_project\\inc

mod1.sonar.projectName=Module1
mod1.sonar.projectBaseDir=mod1
mod1.sonar.sources=.,../mod1_2

mod2.sonar.projectName=Module2
mod2.sonar.projectBaseDir=mod2
mod2.sonar.sources=.

this doesn't seem to work either, the .c file i put in mod1_2 is not recognized. this probably falls in the same category, i just wanted to mention it.

any eta on 0.9.3 ;-)

**Comment by jmecosta** [comment]
cant you just use flat project structure instead of modules? what is the usefullness in your case of modules (we have been questioning yourselfs this for a while)

**Comment by yolani** [comment]
of course i can do this, there is no specific benefit. i just used it because our projects are structured like this, but i can as well use a sonar.sources list containing all source paths.

**Comment by jmecosta** [comment]
this looks to work with last version:

see: https://github.com/jmecosta/sonar-cxx/blob/enhancement/multi-module-with-reactor/integration-tests/testdata/cpp-multimodule-project/sonar-project.properties

21:34:13.331 DEBUG - storing include root: 'C:\dev\sonar-cxx\integration-tests\testdata\googletest_project\tests\gtest-1.6.0\include\gtest'
21:34:13.331 DEBUG - parsing external macro: '__cdecl, '
21:34:13.362 INFO  - storing external macro: '__cdecl -> '''
21:34:13.362 DEBUG - parsing external macro: '__declspec(a), '
21:34:13.362 INFO  - storing external macro: '__declspec(a) -> ',  ''
21:34:13.362 DEBUG - parsing external macro: '__pragma(a), '
21:34:13.362 INFO  - storing external macro: '__pragma(a) -> ',  ''
21:34:13.362 DEBUG - parsing external macro: 'UNITTEST_VERSION 1, '
21:34:13.362 INFO  - storing external macro: 'UNITTEST_VERSION -> '1 ,  ''
21:34:13.362 DEBUG - parsing external macro: 'GTEST_OS_WINDOWS 1'
21:34:13.362 INFO  - storing external macro: 'GTEST_OS_WINDOWS -> '1''
21:34:13.440 WARN  - [c:\dev\sonar-cxx\integration-tests\testdata\cpp-multimodule-project\cli\main.cc:1]: cannot find the sources for '#include <iostream>'
21:34:13.440 DEBUG - [c:\dev\sonar-cxx\integration-tests\testdata\cpp-multimodule-project\cli\main.cc:2]: processing #include "../lib/component1.hh", resolved to file 'C:\dev\sonar-cxx\integration-tests\testdata\cpp-multimodule-project\lib\component1.hh'
21:34:13.456 DEBUG - [c:\dev\sonar-cxx\integration-tests\testdata\cpp-multimodule-project\cli\main.cc:4]: processing #include "gtest.h", resolved to file 'C:\dev\sonar-cxx\integration-tests\testdata\googletest_project\tests\gtest-1.6.0\include\gtest\gtest.h'

can you double check that at least the headers are resolved correctly..

**Comment by jmecosta** [comment]
so what fails is the dependency lookup in multi module
18:48:35.508 WARN  - Unable to find resource 'C:\dev\sonar-cxx\integration-tests\testdata\cpp-multimodule-project\lib\component1.hh' to create a dependency with 'main.cc'
18:48:35.508 WARN  - Unable to find resource 'C:\dev\sonar-cxx\integration-tests\testdata\googletest_project\tests\gtest-1.6.0\include\gtest\gtest.h' to create a dependency with 'main.cc'

**Comment by jmecosta** [comment]
@wenns this fails because the dependencyanalyser is trying to find resource in the same module

File includedFile = File.fromIOFile(new java.io.File(include.getPath()), project);

you had some discussion related with this topic recently with sonar devs, is it so that this is going to be drop.. http://sonarqube.15.x6.nabble.com/sonar-dev-Multi-language-support-for-package-cycles-td5031235.html

**Comment by yolani** [comment]
Exactely, if i delete the include path completely i get another error that the header can not be found.

**Comment by wenns** [comment]
Yes, I had a discussion about a similar topic. The dependecy calculation machinery will undergo heavy changes in the 5.0 series. You can read the details here: #364
@yolani: we are aware of warnings like
```
WARN - Unable to find resource '<path>' to create a dependency with '<filename>' 
```
are a known error in multi module setups. As such setups are not widely used and the mechanism will be changed in the SQ core anyway, we didnt priorize this bug too high...

**Comment by yolani** [comment]
Hi Guys,
sorry for the late response and thanks for the quick answers. so it is a bug in the sonarqube api.

i have switched to a flat project structure in the meantime since i won'T be updating to sonarqube 5.x until there is a lts version.

thanks very much.

greetings,
christian

**Comment by wenns** [comment]
Youre welcome
