### ISSUE TITLE
CxxCoverageSensorTest.shouldReportCoverageWhenVisualStudioCase broken on windows

### ISSUE THREAD

**Issue by jmecosta** [wenns/sonar-cxx#393]
pin pointed to this commit
Commit hash:	3cbb7619a71c90ad17c039b3af6fa58ddb414ad0
Children:	d9dbfaea4a
Parent(s):	7a59321618

Fix tests (type in resource paths)

Contained in branches: report-lookup-performance-fix-draft, master
Contained in tags: cxx-0.9.2

**Comment by guwirth** [comment]
@jmecosta don't understand description above? What exactly is the point here?

**Comment by jmecosta** [comment]
i had some broken tests because of that commit, but i just tried with latest upstream and all is good. likely fixed by a another change
