### ISSUE TITLE
No error message if sonar.cxx.xunit.xsltURL file does not exist

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#396]
If file defined with ```sonar.cxx.xunit.xsltURL``` is not available or can't be read there is no error message.
=> analysis breaks without any hint.

**Comment by wenns** [comment]
Ok. Looks like a good opportunity to try Behavior Driven Development on sonar-cxx (write failing scenario and *then* change production code) ;)

**Comment by guwirth** [comment]
Good idea. Only not sure what the default behavior should be in such a case:
(1) Create an error message and break analysis.
(2) Create an error message and continue analysis.
I tend to (1) because configuration is wrong, please vote.

**Comment by wenns** [comment]
I'm for 1). This is basically status quo + additional logging.
