### ISSUE TITLE
xunit: nested (qualified) classname

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#401]
@wenns I'm nearly ready with the boost integration tests. There is one remaining issue with nested classname. I'm not really sure about the right format in the XML file and if the plugin is handle them in the right way.

What is the format the filename tag should have? Currently it is like ```MyNamespace::MyClass```. I'm using ```::``` as separator. Looking to others they seem to use a ```.``` as separator. But this is not working because you are parsing for ```::```.

```Java
static Pattern classNameMatchingPattern = Pattern.compile("(?:\\w*::)*?(\\w+?)::\\w+?:\\d+$");
String matchClassName(String fullQualFunctionName){ 
   Matcher matcher = classNameMatchingPattern.matcher(fullQualFunctionName);
   String clsname = null;
   if(matcher.matches()){
      clsname = matcher.group(1);
   }
return clsname;
}
```

Here the boost test example (with boost mock):
```C++
//____________________________________________________________________________//
#define BOOST_AUTO_TEST_SUITE(suite_name) namespace suite_name {
#define BOOST_AUTO_TEST_SUITE_END() }
//____________________________________________________________________________//
#define BOOST_AUTO_TEST_CASE(test_name) struct test_name { void test_method(); }; \
void test_name::test_method()
//____________________________________________________________________________//

BOOST_AUTO_TEST_SUITE(my_test_suite)
BOOST_AUTO_TEST_CASE(my_test)
{
   //...
}
BOOST_AUTO_TEST_SUITE_END()
```
After parsing this results in:
```C++
namespace my_test_suite {
   struct my_test { void test_method(); };
   void my_test::test_method() {}
} // namespace
```
The resulting XML file after transformation looks like this:
```XML
<testsuite tests="1" errors="0" failures="0" skipped="0" name="my_module">
  <testcase classname="my_test_suite::my_test" name="test_method" time="0.001" />
</testsuite>
```
I get the error:
```
WARN  - ... no resource found, the testcase 'my_module:my_test_suite::my_test/test_method' has to be skipped
```

**Comment by guwirth** [comment]
Some more questions:
* why are you using group 1 for classname only?
* is there also the method name in the classname tag?
* is this also working with struct?

**Comment by guwirth** [comment]
After some debugging:
* plugin is using internally :: for nested structures
* there is a unit test with namespace showing that only the classname is used and all other parts are stripped away to build the lookup table
* in case of same classname in different namespaces this is a problem

**Comment by guwirth** [comment]
@wenns proposal to add classname with and without namespace(s) in the lookup table should work. What are you thinking?

**Comment by guwirth** [comment]
Any idea how do get the current namespace?
```C++
namespace my_test_suite {
   struct my_test { void test_method(); };
   void my_test::test_method() {}
}
```
I get only ```my_test::test_method:1``` for key. 
```Java
      SourceFile source = CxxAstScanner.scanSingleFileConfig(file, cxxConf);
      if (source.hasChildren()) {
        for (SourceCode child : source.getChildren()) {
          if (child instanceof SourceClass) {
            classDeclTable.put(child.getName(), file.getPath());
          } else if (child instanceof SourceFunction) {
            String clsNameOnly = matchClassNameOnly(child.getKey());
```
Return only two children, there is no namespace?
Could someone help please?

**Comment by wenns** [comment]
Sorry, Guenter, Im not deep into this. Building the lookup table and surroundings is from Jorge, maybe he can answer your questions. Feel free to change this stuff.

**Comment by guwirth** [comment]
Found creation of SourceCode here:

https://github.com/wenns/sonar-cxx/blob/8097bdf7a7f650cd5773f4c18600824282c15371/cxx-squid/src/main/java/org/sonar/cxx/CxxAstScanner.java

```Java
public static AstScanner<Grammar> create(CxxConfiguration conf, SquidAstVisitor<Grammar>... 
    ...  SourceCodeBuilderVisitor<Grammar>
```
Don't know who else is using this? @jmecosta maybe you can remember?

**Comment by jmecosta** [comment]
dont know what is the status of this anymore... :( in the past the lookup table was able to support only cppunit, from what i recall my implementation to support gtest (that i was interested) did not end up committed to master.  from what i recal the class paths for gtest were complety different than cppunit because gtest its mostly macro based. not sure might try to look at the branch in my clone... maybe can find something to help...

**Comment by jmecosta** [comment]
no sorry, could find anymore where that code was.... but from what i remember you cannot use a single implementation to support all test frameworks...
