### ISSUE TITLE
SonarQube vs QT

### ISSUE THREAD

**Issue by AKhachaturian** [wenns/sonar-cxx#404]
Hello, I'm having some trouble using sonar-cxx-0.9.2 with sonarqube 5.0 & QT. I create the simple configuration for analysis:
---------------------------------------------------------------------------------------------
/begin of CPP file
---------------------------------------------------------------------------------------------
#include <QObject>

int main(int argc, char **argv)
{
	QObject* p = new QObject;
	return 1;
}
---------------------------------------------------------------------------------------------
end of CPP file
---------------------------------------------------------------------------------------------
begin of sonar.properties
---------------------------------------------------------------------------------------------
# Required metadata
sonar.projectKey=T1
sonar.projectName=Test 1
sonar.projectVersion=0.0.1

# Language, needed for SonarQube < 4.2
sonar.language=c++

# exclude unit-tests & qt created files
sonar.exclusions=**/ui_*.h

sonar.sources=./1

# Path to included files
sonar.cxx.include_directories=C:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/include,D:/Qt/qt-5.4.0-x64-msvc2012-opengl/qt-5.4.0-x64-msvc2012-opengl/include/QtCore
sonar.cxx.library.directories=D:/Qt/qt-5.4.0-x64-msvc2012-opengl/qt-5.4.0-x64-msvc2012-opengl

# Encoding of the source files
sonar.sourceEncoding=UTF-8
---------------------------------------------------------------------------------------------
end of sonar.properties
---------------------------------------------------------------------------------------------
where './1' path to my CPP file & 'D:/Qt/qt-5.4.0-x64-msvc2012-opengl/qt-5.4.0-x64-msvc2012-opengl/' path to my QT directory. In result I give next errors:
---------------------------------------------------------------------------------------------
07:18:13.382 WARN  - [d:\src\DxO\FilmPack5\modules\1\1.cpp:1]: cannot find the sources for '#include <QObject>'
07:18:13.399 ERROR - Unable to parse file: d:\src\DxO\FilmPack5\modules\1\1.cpp
07:18:13.401 ERROR - Parse error at line 3 column 9:

  -->  int main(int argc, char **argv)
    4: {
    5:  QObject* p = __newQObject;
    6:  return 1;
    7: }EOF
---------------------------------------------------------------------------------------------
May be someone can told me what the problem?

**Comment by guwirth** [comment]
V0.9.2 is not tested and released with SQ 5, see https://github.com/wenns/sonar-cxx/wiki/SonarQube-compatibility-matrix

**Comment by AKhachaturian** [comment]
sure, also also I found configuration error in 'properties'-file ('sonar.cxx.include_Directories' instead of 'sonar.cxx.includeDirectories'). Now almost all good except 'cannot find the sources for' warnings for QT headers. Do you can give me advice how it should be fix?

**Comment by guwirth** [comment]
Please have a look to our wiki: https://github.com/wenns/sonar-cxx/wiki

* Dealing with compiler specific code peaces: https://github.com/wenns/sonar-cxx/wiki/Dealing-with-compiler-specific-code-peaces
* Detect and fix parsing errors: https://github.com/wenns/sonar-cxx/wiki/Detect-and-fix-parsing-errors
* ...

**Comment by guwirth** [comment]
Close this. Please reopen if this is still an issues.
