### ISSUE TITLE
Commercial CPP plugin together with CXX plugin

### ISSUE THREAD

**Issue by chrissy25** [wenns/sonar-cxx#406]
Hi,

is there an easy way to make this plugin compatible with the commercial version of the CPP plugin?
We would like to use the commercial version of the plugin, together with the features of the CXX plugin. For example we would like to have also the PC-Lint import functionality and also the coverage sensor of CXX is much better than in the commercial version.

Best regards
Chrissy

**Comment by guwirth** [comment]
First of all thanks for the positive feedback.

> make this plugin compatible with the commercial version

What do exactly mean with make it compatible?
* Same configuration?
* Usable in parallel?
* Using only some parts (sensors) of this plugin?
* ...

**Comment by chrissy25** [comment]
We would like to use both plugins in parallel.
The CXX rule repositories should be added to the C++ and C language rules. So that we can use all Sensors of CXX and of the commercial version.

For example:
We have some PC-Lint reports and want to integrate it to our results, which we are getting from the CPP plugin. I created an own plugin for PC-Lint based on your PC-Lint module and this is working fine. This plugin adds your PC-Lint rule repository to the language C and will analyze the PC-Lint reports and add the issues (as in your module ;) ).

But I have done this only for PC-Lint and also all other features of CXX would be nice :) And I think it would be much easier, when CXX can also support this out of the box, and I think we are not the only users which would like to have it :)


Until now I had discovered two blocking points:
- SonarQube has a problem to use the right plugin for a C/C++ file, because there are two plugins which are analyzing those files
- All rule repositories have to be added to the language C AND C++

**Comment by guwirth** [comment]
I think this is not possible.
* SQ decides over the file extension which plugin should be used. Commercial and community plugin are configured both to use .C, .CPP, ... as source.
* Currently all sensors of a plugin are executed. In case this should work both plugins need a possibility to turn individual sensors on or off.

Maybe easier to fork this repository and do cherry picking of the sensors you need?

Last question just for interest: What is better with the commercial plugin? What is missing in this one?

**Comment by guwirth** [comment]
Close this. Please reopen if this is still an issue.
