### ISSUE TITLE
Parse warnings from gcc compiler

### ISSUE THREAD

**Issue by iwill80** [wenns/sonar-cxx#416]
Hello, 
I'm having some trouble parsing the warning from the gcc compiler. As suggested in the wiki page, I compiled my project redirecting the output into a file (build.log) and I configured the following properties:

sonar.cxx.compiler.parser=GCC
sonar.cxx.compiler.reportPath=build.log
sonar.cxx.compiler.charset=UTF-8
sonar.cxx.compiler.regex=^(.*):([0-9]+):[0-9]+: warning: (.*)\\[(.*)\\]$

There are many warning after compilation, but they are not processed.

12:49:11.164 INFO  - Scanner 'GCC' initialized with report 'xxx/build.log', CharSet= 'UTF-8'
12:49:11.197 INFO  - C-Compiler warnings processed = 0

I think that there is something wrong in the regular expression, but I cannot find the right one (I'm not so familiar with them). What I'm wrong?
I've also tried to leave the sonar.cxx.compiler.regex to the default value, but the result is the same.

The followings are some example of warning that I found in build.log file

../include/tcn.h:253: warning: function declaration isn’t a prototype
../include/hpn.h:98: warning: conversion to ‘long int’ from ‘long unsigned int’ may change the

Can somebody suggest me the right regular expression?

**Comment by Bertk** [comment]
Please read the wiki https://github.com/wenns/sonar-cxx/wiki/Compilers
The unit test for gcc uses this sample output file https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/test/resources/org/sonar/plugins/cxx/reports-project/compiler-reports/build.log
The regular expression extracts 4 groups from the warning message
1. file name
2. line number
3. rule ID
4. warning message

e.g.
```sonar.cxx.compiler.regex=^(.*):(\\d+):\\d+: warning: (.*)\\[(.*)\\]$```will match the following line
```
/home/test/src/zip/src/zipmanager.cpp:271:75: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
```
and extract
```
/home/test/src/zip/src/zipmanager.cpp
271
comparing floating point with == or != is unsafe 
-Wfloat-equal
```
Please note: within the setting *sonar.cxx.compiler.regex* the '\' in the regular expression has to be quoted and becomes '\\\\'

**Comment by Typz** [comment]
Hello,

The default regexp should be OK, but you need to add the '-fdiagnostics-show-option' option in your GCC build, so that the type of warning is shown at the end of each warning line.

I will update the wiki to properly indicate this.

**Comment by iwill80** [comment]
Hello, 
Thank you for your support! While the default regexp doesn't work for me neither with the '-fdiagnostics-show-option', the following is instead fine:

```
sonar.cxx.compiler.regex=^(.*):(\\d+): warning: (.*)\\[(.*)\\]$
```

to parse the following format:

```
xxx.x:1056: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
```

Thank you

William
