### ISSUE TITLE
sonar.cxx.defines regressions in v 0.9.2

### ISSUE THREAD

**Issue by franckbonin** [wenns/sonar-cxx#417]
sonar.cxx.defines use to support multiple define in on line :

in v0.9n content like  "__declspec(x), EXPORTSPEC, DECL2, afx_msg, WINAPI, sealed, final," 
was correctly parsed :
03:53:38 [DEBUG] [03:54:28.336] parsing external macro: '__declspec(x)'
03:53:38 [INFO] [03:54:28.336] storing external macro: '__declspec(x) -> '''
03:53:38 [DEBUG] [03:54:28.336] parsing external macro: 'EXPORTSPEC'
03:53:38 [INFO] [03:54:28.336] storing external macro: 'EXPORTSPEC -> '''
03:53:38 [DEBUG] [03:54:28.337] parsing external macro: 'DECL2'
03:53:38 [INFO] [03:54:28.337] storing external macro: 'DECL2 -> '''
03:53:38 [DEBUG] [03:54:28.337] parsing external macro: 'afx_msg'
03:53:38 [INFO] [03:54:28.337] storing external macro: 'afx_msg -> '''
03:53:38 [DEBUG] [03:54:28.337] parsing external macro: 'WINAPI'
03:53:38 [INFO] [03:54:28.337] storing external macro: 'WINAPI -> '''
03:53:38 [DEBUG] [03:54:28.338] parsing external macro: 'sealed'
03:53:38 [INFO] [03:54:28.338] storing external macro: 'sealed -> '''
03:53:38 [DEBUG] [03:54:28.338] parsing external macro: 'final'
03:53:38 [INFO] [03:54:28.338] storing external macro: 'final -> '''

in v0.9.2 it became :
16:18:57 [DEBUG] [16:19:50.573] parsing external macro: '    __declspec(x), EXPORTSPEC, DECL2, afx_msg, WINAPI, sealed, final,'
16:18:57 [INFO] [16:19:50.573] storing external macro: '__declspec(x) -> ',   EXPORTSPEC ,   DECL2 ,   afx_msg ,   WINAPI ,   sealed ,  

In v0.9n content like 
" TRY try,
   CATCH(x\,y) catch(x y)," 
was correctly parsed :
03:53:38 [DEBUG] [03:54:28.316] parsing external macro: 'TRY try'
03:53:38 [INFO] [03:54:28.316] storing external macro: 'TRY -> 'try''
03:53:38 [DEBUG] [03:54:28.316] parsing external macro: 'CATCH(x,y) catch(x y)'
03:53:38 [INFO] [03:54:28.317] storing external macro: 'CATCH(x, y) -> 'catch ( x   y )''

in v0.9.2 it became :
17:02:14 [DEBUG] [17:03:07.419] parsing external macro: '    TRY try,'
17:02:14 [INFO] [17:03:07.419] storing external macro: 'TRY -> 'try ,''
17:02:14 [DEBUG] [17:03:07.419] parsing external macro: '    CATCH(x\,y) catch(x y),'
17:02:14 [INFO] [17:03:07.419] storing external macro: 'CATCH -> '''

Moreover macro replacement is some time strange in v0.9.2 :
with sonar.cxx.defines : 
17:02:14 [DEBUG] [17:03:07.427] parsing external macro: '    __declspec(x),'
17:02:14 [INFO] [17:03:07.427] storing external macro: '__declspec(x) -> ',''

code like :
class JSONRPC_EXPORT Client
{
    public:
//...
};
//JSONRPC_EXPORT define in an header file as #define JSONRPC_EXPORT __declspec(dllexport)

is parsed as :

[ERROR] [17:01:59.180] Parse error at line 44 column 10:
17:01:06 
17:01:06    33: namespace Json
17:01:06    34: {
17:01:06    35: 
17:01:06    36:   namespace Rpc
17:01:06    37:   {
17:01:06    38:     struct ClientPrivate;
17:01:06    39: 
17:01:06    40: 
17:01:06    41: 
17:01:06    42: 
17:01:06    43: 
17:01:06   -->      class ,              Client
17:01:06    45:     {
17:01:06    46:       public:

**Comment by wenns** [comment]
Its a feature ;)
Jokes aside: the new syntax is documented [here](https://github.com/wenns/sonar-cxx/wiki/Supported-configuration-properties) and is like this:
```
sonar.cxx.defines=macro (p1, p1) value \n\
       macro2(n1, n2) value2 \n\
       ...
```
We dont particularly like it but thats the only known way to support multi-line widgets in the web interface *and* the config file.

**Comment by guwirth** [comment]
Close this. Please reopen if this is still an issue.
