### ISSUE TITLE
What is sslr-cxx-toolkit-0.9.2 for?

### ISSUE THREAD

**Issue by huangye177** [wenns/sonar-cxx#419]
Hi guys,

I am confused by the installation page, since I am not sure whether I need "sslr-cxx-toolkit-0.9.2.jar" to be moved to extenions/plugins as well for a complete installation of CXX. 

Do I need it? What is this package (indeed, only one file) for?

Cheers, 
Ye

**Comment by Bertk** [comment]
The file *sslr-cxx-toolkit-0.9.2.jar* shall not be copied to *extensions/plugins* folder.
You can use the jar file to parse source code snippets and evaluate SSLR XPath queries. 

The command line ```Java -jar sslr-cxx-toolkit-0.9.2.jar``` will start the GUI


![capture](https://cloud.githubusercontent.com/assets/2315215/6031487/18756eee-ac00-11e4-88a0-e2c0473a1286.JPG)

**Comment by huangye177** [comment]
Thanks a lot!
