### ISSUE TITLE
Documentation Coverage / Parse Errors

### ISSUE THREAD

**Issue by LewisDeacon** [wenns/sonar-cxx#420]
Hi Guys, 

Recently it came to my attention that the documentation coverage results on my projects' dashboard was incorrect by quite a big margin, this caused me to investigate the problem a bit further. I found when running sonarrunner that every so often I was getting Parse errors, particularly so on the files that I expected to have commented lines accounted for on the SonarQube dashboard.

My Questions are:

1. Files that have parse errors are disregarded for Documentation / Comment line coverage?

2. The section of the file that is unable to parse on 90% of my parse errors is "struct __declspec ( dllimport )SVersion" in which I read about the ForceInclude property to ensure my defines.h file was included. However I have had no such luck with this, is there something I am missing or could do to 1) Stop the parse errors and 2) Improve the documentation metrics on my dashboard?

*EDIT*
3. I have also tried the Error Recovery property, which has given different but positive results, my worry is that from this link (https://github.com/wenns/sonar-cxx/wiki/Detect-and-fix-parsing-errors) there is a comment stating that this could result in accuracy loss, Accuracy loss in what ? Will this hinder the accuracy of finding violations?

Thanks in advance,
Lewis

**Comment by guwirth** [comment]
Hello Lewis,

> 1/3...

To get good documentation coverage the plugin must be able to parse the source code. The functionality needs a valid AST.
* Without ErrorRecovery turned on the parser stops parsing after the first syntax error. The rest of the file is ignored (not part of the AST)
* With ErrorRecovery the parser continues after a syntax error with the next declaration. Only the declaration with the syntax error is ignored.
The comment with 'accuracy loss' means that ErrorRecovery gets you worse results compared to a file which could be parsed without syntax errors.

> 2 ...

Could you provide a complete example please.
"struct __declspec ( dllimport )SVersion" 

Regards,

**Comment by LewisDeacon** [comment]
@guwirth 

Thanks a lot for the reply. 

Thanks for the clarification, the comment regarding the accuracy loss makes sense - I just wanted to be sure that I was not going to be getting false positives/negatives with using the ErrorRecovery property. I have seen much better documentation coverage with using the ErrorRecovery property obviously it is not the best because there are blocks of code being missed because of the Syntax Error but I think your answer to 1) and 2) give me enough clarification without having to post a complete example of the "struct __declspec ( dllimport )SVersion".


Thanks a lot
Lewis

**Comment by guwirth** [comment]
A last hint: Are there really blanks behind ```__declspec``` and before the ```(```?
For macros the  left parenthesis must be directly after the macro-name. Maybe this is the reason the mocking is not working?
```C++
struct __declspec(dllimport) SVersion ...
```

**Comment by LewisDeacon** [comment]
@guwirth The actual code does not have the spaces but I copy and pasted that line from the console log of the Jenkins build. I am not sure where those spaces are coming from ? Does the plugin try to substitute the macro definition into the code in order to parse it - is that adding the spaces?

Cheers
Lewis
