### ISSUE TITLE
xunit, filename tag: relative paths are not supported

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#427]
**V0.9.3 alpha:**  After refactoring relative paths in filename tags seems to be no more supported.

File: https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/xunit/DefaultResourceFinder.java
```Java
List<File> files = Lists.newArrayList(fs.files(fs.predicates().is(file)));
```
Also test cases seems to be missing?

@wenns You did the refactoring. Did you test this with relative paths in filename tag?

**Comment by wenns** [comment]
Sorry for disappearing, there are times I dont have spare time for this project... Having a look at this.

**Comment by guwirth** [comment]
checked it again:
```Java
fs.predicates().is(file)
```
is supporting absolute & relative paths
