### ISSUE TITLE
org.sonar.api.utils.SonarException: XML is not valid 

### ISSUE THREAD

**Issue by senthilmuniyan** [wenns/sonar-cxx#432]
Hi Sonar-cxx Experts,

Any help appericated.

Problem:
-------------
I have created custom rules for sonar-cxx plugin, but not able to import the custom rules.(sonarqube is not able to start )

Error:
----------
2015.02.27 20:21:54 INFO  localhost-startStop-1 web[org.sonar.INFO]  Register rules done: 624 ms
2015.02.27 20:21:54 INFO  localhost-startStop-1 web[o.s.s.n.NotificationService]  Notification service stopped
2015.02.27 20:21:54 ERROR localhost-startStop-1 web[o.a.c.c.C.[.[.[/]]  Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
org.sonar.api.utils.SonarException: XML is not valid
	at org.sonar.api.rules.XMLRuleParser.parse(XMLRuleParser.java:113) ~[sonar-deprecated-4.5.2.jar:na]
	at org.sonar.plugins.cxx.utils.CxxAbstractRuleRepository.createRules(CxxAbstractRuleRepository.java:75) ~[na:na]
	at org.sonar.server.rule.DeprecatedRulesDefinitionLoader.complete(DeprecatedRulesDefinitionLoader.java:92) ~[sonar-server-4.5.2.jar:na]
	at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:53) ~[sonar-server-4.5.2.jar:na]
	at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:102) ~[sonar-server-4.5.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]

My system configurations:
-----------------------------------
sonarqube - 4.5.2
cppcheck - 1.68
sonar-cxx-plugin-0.9.1
Windows - 64 bit

My custom rulefile: (cppcheck.xml) 
----------------------------------------------------

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<rules>
  <rule key="Rule1">
    <name><![CDATA[Rule1]]></name>
    <configKey>
      <![CDATA[Rule1@$(SomeDir)\Rules\Rules.dll]]>
    </configKey>
    <category name="Maintainability" />
    <description>
      <![CDATA[Data context must not be set in XAML. This way it's made sure that a view always has 1:1 relationship with the respective viewmodel. Resolution: Remove data contexts attributes. Application engine takes care of matching views and view models automatically, based on a naming convention.]]>
    </description>
  </rule>
</rules>

Additional Configurations:
---------------------------------

1. Updated the sonar.properties file from (sonar-root-dir\conf\)

sonar.cxx.cppcheck.customRules=cppcheck.xml

Senthilkumar M

**Comment by jmecosta** [comment]
hi,
sonar.cxx.cppcheck.customRules is to be used during analysis, with a results file. the xml snippet you add needs to be added to the web ui  configuration. we no longer support xml in (sonar-root-dir)

see https://github.com/wenns/sonar-cxx/wiki/Extending-the-code-analysis

**Comment by senthilmuniyan** [comment]
Thanks a lot.
It worked nice.
