### ISSUE TITLE
Sonar not showing any issues for C analysis

### ISSUE THREAD

**Issue by Vishaka10** [wenns/sonar-cxx#438]
Hi,

I am using SonarQube Version 4.3.2 for static analysis. I trying to generate the SA results for C code using cppcheck in Jenkins and passing this generated report.xml file to sonar to try and get the issues reflected on sonar. Although the files are being analyzed it showing 0 issues.
However I found that the ccpcheck running on Jenkins shows a lot of issues.

Could you please help me get a resolution for the same?

Thanks,
Vishaka

**Comment by guwirth** [comment]
> Turn debug info on and analyze the log file https://github.com/wenns/sonar-cxx/wiki/Get-debug-information

If the plugin is able to read the report it is mostly a path issue https://github.com/wenns/sonar-cxx/wiki/Path-and-path-separator-issues

**Comment by Vishaka10** [comment]
Hi Gunter,

Thanks for your response. I am using the absolute path instead of the relative path.
Also,  I found that only one issues is being shown on Sonar, missing include files, although there are a lot of issues being shown by the cppcheck analysis.

I am running the analysis for C code. Do I have to set any parameters for that?

Thanks,
Vishaka

**Comment by guwirth** [comment]
* Are the cppcheck rules enabled in your quality profile?

* Did you try to create debug info (see above)?
  * Did the plugin read the source code files (verify log file)?
  * Is the plugin able to read the cppcheck report (verify log file)?
   * Are there any additional error messages/hints in the log file?

**Comment by Vishaka10** [comment]
Hi Gunter,

It works fine now. I changed the path and tried running it on a different server and it worked.
Thanks for your help.

Thanks,
Vishaka
