### ISSUE TITLE
Already created edge from file x to file y

### ISSUE THREAD

**Issue by yolani** [wenns/sonar-cxx#439]
HI there,

i have a question about a warning i get from the plugin. i recently started disabling some of the rules in the default rule set and now when i rerun the analysis for my projects i get the warning "Already created edge from File1 to File2".

I looked at the code in the repository but can't really figure out what this warning is trying to tell me.

Any help would be great.

**Comment by guwirth** [comment]
Looking to the log file: in which sensor do you get the message?

Von meinem iPhone gesendet

**Comment by yolani** [comment]
I get the warning in the CxxSquidSensor

**Comment by guwirth** [comment]
https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/squid/DependencyAnalyzer.java

@typz wrote this

**Comment by yolani** [comment]
I already saw this, bit i am not sure i do understand it. 

does it say that the sensor detected a violation for a disabled rule?

**Comment by Typz** [comment]
No, this is not related to any rule, nothing's wrong in your code here.

It just seems a bit strange, since we use maps to store the relationship, I
believe (or I believed when I wrote this) that this could/should not
happen. Anyway, in worse case this could only affect the 'weight' of a
dependency, nothing so bad...

Do you have a use case to reproduce this? (e.g. which file includes which
one...)

**Comment by yolani** [comment]
Hi there,

sorry for the late response, but work has been a bit hectic in the last few days. unfortunately we are talking about code from my company, so i can not just let you look into this.

i will try to produce a dummy example that has a similar include structure. i hope to get it done before the weekend.

**Comment by yolani** [comment]
Hi there,

i managed to reproduce the problem with a simple example. the warning seems to appear if i include a header in one file more then once, even if the header has re-include protection.

unfortunately this scenario is a use-case in our software. please don't ask me why, i hate it myself but there is nothing i can do about it. this has "historic reasons" ;-)

but what i still don't get is why this occurs if i start disabling some rules from the c++ repository. if i enable all of them i don't get this warning.

**Comment by Typz** [comment]
There is indeed a rule that detects when the same file is included multiple times.

I'll try to check how disabling the rule causes the warning.
