### ISSUE TITLE
cxx:UseFileHeader How to use?

### ISSUE THREAD

**Issue by chrissy25** [wenns/sonar-cxx#440]
Hi, I have a problem to use the rule "Copyright and license headers should be defined in all source files". When I specify only one line it works fine, but when I try to specify more than one line, Sonar is not able to identify my header ...
I tried to use "\n" for a new line, or just plain text ... but it is not working, when I want to configure more than one line as a header/copyright ...

**Comment by guwirth** [comment]
Just guessing:
- Newline is not newline, could be \n, \r or \r\n. Please check your source file. 
- Try also with \\n or \n\

**Comment by chrissy25** [comment]
Ok seems not to work, even if I use the example, which is provided in this rule it is not working ...

**Comment by guwirth** [comment]
@Zetten maybe you can help?
https://github.com/wenns/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/FileHeaderCheck.java

**Comment by guwirth** [comment]
Or as workaround you can try File RegEx
https://github.com/wenns/sonar-cxx/wiki/Create-Custom-Rules

**Comment by Zetten** [comment]
This looks like the issue I was trying to fix with my commit (914a7f2) to FileHeaderCheck. With this you definitely get the multiline textbox input. However my commit wasn't merged until after 0.9.2 so unless you've built sonar-cxx from source you won't have it.

But I've just noticed that one of my devs has disabled the rule in their project profile, so I will have to check if it's misbehaving somehow. More likely is some regex issue with their complex header rule though.

**Comment by Zetten** [comment]
We've just re-enabled the rule in our profile and it works as expected - a multiline input when configuring, and it seems to correctly validate.

So it should definitely be fixed in the next release, or you can cherry-pick 914a7f2 to a custom plugin build.

**Comment by guwirth** [comment]
fixed, see https://github.com/wenns/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/FileHeaderCheck.java
