### ISSUE TITLE
Unable to parse UTF-8 with BOM files

### ISSUE THREAD

**Issue by ASolovyev** [wenns/sonar-cxx#443]
In a sonar 4.5.4 +  C++ community plugin we have an issue while parsing UTF-8 with BOM files.

[14:40:00][Step 1/18] 14:39:05.577 ERROR - Parse error at line 1 column 0:
[14:40:00][Step 1/18]
[14:40:00][Step 1/18] --> ï»¿
[14:40:00][Step 1/18] 2: namespace foo

**Comment by guwirth** [comment]
Already discussed, see #223.

**Comment by ASolovyev** [comment]
I've already read this issue. But i have latest (v 0.9.2) version of plugin and result  is same. files with BOM are unable to parse:

[14:19:02][Step 1/18] 14:18:06.333 ERROR - Parse error at line 1 column 0:
[14:19:02][Step 1/18]
[14:19:02][Step 1/18] --> ï»¿
[14:19:02][Step 1/18] 2:
[14:19:02][Step 1/18] 3:
[14:19:02][Step 1/18] 4:
[14:19:02][Step 1/18] 5:
[14:19:02][Step 1/18] 6: namespace foo

**Comment by guwirth** [comment]
The statement there is that the SonarQube core is responsible for reading a file and not the plugin.

* Set the right encoding in your project settings. Which setting do you use?
* Do all files have the same encoding?

**Comment by ASolovyev** [comment]
Yes. All files are same encoding and C# Projet uses UTF8 With bom.
We took a python script which deletes BOM from files before Sonar starts. And now everything is ok.

**Comment by guwirth** [comment]
Sounds really strange especially because C# seems to be able to handle UTF-8 with BOM. Change label to error. We should to some further investigation.

**Comment by guwirth** [comment]
Seems to be also an issue with C#:
http://stackoverflow.com/questions/29368545/sonar-c-sharp-plugin-unable-to-parse-files-utf-8-with-bom
http://stackoverflow.com/questions/29122969/sonarqube-c-community-plugin-utf-8-with-bom-parsing

**Comment by guwirth** [comment]
see PR #450: fails
=> seems to be really a platform issue

**Comment by ASolovyev** [comment]
yes it seems. we analyzed lots of source. Sonar fails with utf-8 BOM files and it not depends of plugin.
So, now we are usin g a bom-remover script.

**Comment by guwirth** [comment]
Can only recommend to create an SQ feature request for this. All what we can do is to document this limitation.

**Comment by guwirth** [comment]
documented, see https://github.com/wenns/sonar-cxx/wiki/FAQ

**Comment by ASolovyev** [comment]
Thank you!

-- 
С уважением, Соловьев Алексей.


22.04.2015, 18:17, "Günter Wirth" <notifications@github.com>:
