### ISSUE TITLE
Test success not shown

### ISSUE THREAD

**Issue by wichtounet** [wenns/sonar-cxx#444]
Hello, 

First of all, congratulations for the new version of the plugin it is much better!

I've integrated a junit report into my project. Nothing is shown in the dashboard. I also have code coverage report which works perfectly. 

The report looks like that: 

```xml
<testsuites>
   <testsuite name="all tests" errors="0" failures="2" tests="8359" hostname="tbd" time="0.091043" timestamp="tbd">
       <testcase classname="magic/dyn_matrix_1" name="double" time="0.000189"/>
       <testcase classname="magic/dyn_matrix_2" name="double" time="0.000045"/>
      <testcase classname="magic/dyn_matrix_3" name="double" time="0.000052"/>
       <testcase classname="magic/dyn_matrix_4" name="double" time="0.000033"/>
       ...
```

It is completely valid according to your rnc file, but it is mostly additional arguments, I don't think this should give you any problem. The only thing I've seen that could cause a problem is that some <testcase> have multiple <failure>, is that an issue ? 

It seems to have been parsed: 

> 10:43:54.476 INFO  - Processing report '/data/jenkins/.jenkins/workspace/etl/./catch_report.xml'
> 10:43:54.476 INFO  - Parsing report '/data/jenkins/.jenkins/workspace/etl/./catch_report.xml'
> 10:43:54.674 INFO  - Sensor CxxXunitSensor done: 204 ms

Is there something more than I have to do ? 

Thanks

**Comment by guwirth** [comment]
Have you seen this https://github.com/wenns/sonar-cxx/wiki/Get-test-execution-metrics?
* turn debug info on to get more details https://github.com/wenns/sonar-cxx/wiki/Get-debug-information
* Which mode are you using (sonar.cxx.xunit.provideDetails)?
* Unit test files must exist in detailed mode (sonar.tests)

**Comment by wichtounet** [comment]
I have seen and read this, yes. 

With debug output, nothing of interests shows up for unit tests. Only lots of messages indicating that the source files are no found and dummy ones are created. 

I'm using the default mode (simple).

**Comment by jmecosta** [comment]
your report looks a bit weird... the name is repeated for all test cases and a status tag is missing... see
https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/test/resources/org/sonar/plugins/cxx/reports-project/xunit-reports/xunit-result-2.xml

not completly sure if thats the reason

**Comment by wichtounet** [comment]
That may be it, this is because Catch has the notion of section, therefore the name is the name of the section, while classname is the name of the test. I'll try to concat both and see if it works better.

**Comment by wichtounet** [comment]
I tested by adding status="run" to all testcase. I also tried with concatenating classname and name, but this didn't change a thing. 

The only thing that remains in the output is 

Cannot find the source file for test 'all', creating a dummy one

**Comment by jmecosta** [comment]
i dont find anywhere in code the place where that message would be created, if not mistaken the latest version does not create dummy files anymore because those are not supported by the platform. when setting the mode to simple the plugin should only gather metrics and not try to find the source for the test. can you  double check what version of the plugin you are using

**Comment by wenns** [comment]
The new version should not talk about 'creating dummy files' in the logs. Can you double check the plugin version you're using?

**Comment by wichtounet** [comment]
That was the issue indeed :( My Sonar instances got mixed for some reason and I ended up uploading to the wrong one. Now it works :)

Just one more question though: How is the Execution time computed ? In my case, it seems off by an order of magnitude.

**Comment by guwirth** [comment]
As fare as I know the SQ core is doing this. So maybe you should ask this question in the SQ forum.

**Comment by guwirth** [comment]
Looking forward to hear your opinion about the cxx plugin 0.9.2 (http://baptiste-wicht.com/posts/2014/10/sonarqube-inspections-for-cpp-projects.html).

**Comment by wichtounet** [comment]
It seems I'm not the only one having issues with the test execution time, so I'll check with SQ, but that is not important. 

I will post something on the blog. 

Thanks a lot for the help.
