### ISSUE TITLE
What cause this error: 'NoSuchFieldError: COMMENT_BLANK_LINES' ?

### ISSUE THREAD

**Issue by pqcyylu** [wenns/sonar-cxx#447]

**Comment by guwirth** [comment]
Could you provide some more information please?
Which SonarQube version are you using?
Which version of the Cxx plugin are you using?
Where and when do you get the error?

**Comment by guwirth** [comment]
See #395

**Comment by Bertk** [comment]
See https://github.com/wenns/sonar-cxx/pull/423. The metric 'Blank comments' is deprecated. Please check history of http://docs.sonarqube.org/display/SONAR/Metric+definitions

**Comment by pqcyylu** [comment]
Thanks all. upgrade to version 0.9.3, this problem is gone.
