### ISSUE TITLE
Typed constants are detected as magic numbers

### ISSUE THREAD

**Issue by Phyks** [wenns/sonar-cxx#463]
Hi,

Not sure if a bug or a feature but typed constants are detected as magic numbers, however MISRA specification forces the use of typed constants.

For instance, 0 and 1 are not considered as magic numbers by sonar-cxx. But `0U`, `0F` and so on are detected as magic numbers.

**Comment by guwirth** [comment]
> For instance, 0 and 1 are not considered as magic numbers by sonar-cxx. But 0U, 0F and so on are detected as magic numbers.

The check has default exceptions "0,1,0x0,0x00,.0,.1,0.0,1.0". Why not just adding 0U and 0F to your settings?

**Comment by Phyks** [comment]
Indeed, that could be a solution. Is there a way to override it in the config, without modifying the source file https://github.com/wenns/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/MagicNumberCheck.java?

Thanks

**Comment by guwirth** [comment]
Yes in the configuration of your server: Settings/Rules.

**Comment by Phyks** [comment]
Indeed, I missed configuration at this place, my bad =(

Thanks a lot!
