### ISSUE TITLE
Parse error with errno

### ISSUE THREAD

**Issue by Phyks** [wenns/sonar-cxx#465]
Hi,

The following code generates a parser error in sonar-cxx:
```
#include <cerrno>
#include <cstdio>

ty::int64_t int64OfString(ty::char_t const str[])
{
	char* end = NULL;
	const ty::int64_t result = std::strtol(str, &end, 10);

	if (end == str || ERANGE == errno)
	{
		// TODO
	}
	return result;
}
```

AFAIK, this is due to the presence of `ERANGE == errno` as the error disappear if I remove this test from the if condition. This code compiles just fine using gcc.

Thanks

**Comment by guwirth** [comment]
Looks more like header files could not be found (sonar.cxx.includeDirectories and sonar.cxx.defines)?
See https://github.com/wenns/sonar-cxx/wiki/Running-the-analysis.

**Comment by Phyks** [comment]
I have some error due to includes indeed, sorry I missed the feedback on #437.

But I only get the issue described here with `errno` which make me think it is not an includeDirectories or define problem, especially as I heavily use other features from the STL.

**Comment by Phyks** [comment]
Ok, I confirm this error was due to #437, this is now solved, thanks a lot!
