### ISSUE TITLE
Document changes related with c++ SonarQube c++ rules 

### ISSUE THREAD

**Issue by jmecosta** [wenns/sonar-cxx#472]
After restoring a profile from the previous version, there are less 10 rules in the SonarQube rules repository. 

Some have name changes, 
Files should not be too complex
Functions should not be too complex
Line RegEx rule
File RegEx rule
Tabulation characters should not be used
TODO tags should be handled
FIXME tags should be handled
IP addresses should not be hardcoded

some do no exist anymore
Comment regular expression rule

Can you guys verify this also happens to you

**Comment by guwirth** [comment]
* Testing with SQ 4.5.4 I see 39 rules in 'c++ SonarQube'
* I changed some rule names to unify class name, rule key and html file name. If this is critical I can change it back.
* 'Regular expression on comment' is visible

**Comment by jmecosta** [comment]
Yes the rules are there. Issue is that after you upgrade the rules that had
names changed will be diaable. I dont mind however needs to be documented
which ones changed

**Comment by guwirth** [comment]
There is this @ActivatedByDefault.  Anyway don't know for which checks we should set this?

> Am 18.04.2015 um 14:15 schrieb Jorge Costa <notifications@github.com>:
> 
> Yes the rules are there. Issue is that after you upgrade the rules that had
> names changed will be diaable. I dont mind however needs to be documented
> which ones changed
>

**Comment by jmecosta** [comment]
You did not understand, say I had 20 rules from this repo enabled before
upgrading in profile x. After upgrading profile x will have less y rules
enabled because the ids have been modified. You can not express in code the
relation between old and new ids so in fact those rules that had the names
changed are, for sonar, totally new rules.

Perhaps the ids should be reverted to ensure this does not happen. I for
example had to go to old instance and compare by the names what are the new
names and enable those again in the relevant profiles. As an example the
complexity rules are totally different and those will raise questions.

For the rules enabled by the default, all can be enabled by default imo

**Comment by guwirth** [comment]
I think main problem are **templates rules** were @ActivatedByDefault is not set **and** are renamed.

**Comment by jmecosta** [comment]
those are ok imo, since the ids of such rules are managed by sonar and do not depend on the plugin definition. meaning once defined (and assuming plugin is not removed) the rules are always found in database. 

but there are 2 things here... 

1. activated by default -> all rules that are not template rules should have @ActivatedByDefault

2. rules that are not template rules should not have their ids changed from a version another since it causes profiles to be different after upgrading

**Comment by guwirth** [comment]
Changed rule keys (old => new):
* FileCyclomaticComplexity => FileComplexity
* InvalidFileEncoding => FileEncoding
* UseFileHeader => FileHeader
* NotAllowedFixMeTag => FixmeTagPresence
* FunctionCyclomaticComplexity => FunctionComplexity
* NoHardcodedAccount => HardcodedAccount
* NoHardcodedIp => HardcodedIp
* IndentationCheck => Indentation
* MissingInclude => MissingIncludeFile
* NewLineAtEOF => MissingNewLineAtEndOfFile
* ReservedNamesCheck => ReservedNames
* SafetyTagCheck => SafetyTag
* SwitchLastCaseIsDefaultCheck => SwitchLastCaseIsDefault
* NoTabCharacter => TabCharacter
* NotAllowedToDoTag => TodoTagPresence

**Comment by jmecosta** [comment]
Should be placed in pdwiki and a link in the changes so its easy to spot by
users. Otherwise list is good.

**Comment by guwirth** [comment]
See still two possibilities: Document & keep it -or- change key back to old one.

**Please vote**

**Comment by jmecosta** [comment]
Since they are not many +1 keep and document.

**Comment by guwirth** [comment]
documented, see https://github.com/wenns/sonar-cxx/wiki/Upgrade-Instructions
