### ISSUE TITLE
should internal parsers error generate debt?

### ISSUE THREAD

**Issue by jmecosta** [wenns/sonar-cxx#475]
@Rule(
  key = "ParsingError",
  name = "C++ parser failure",
  priority = Priority.MAJOR)
@SqaleSubCharacteristic(RulesDefinition.SubCharacteristics.INSTRUCTION_RELIABILITY)
@SqaleConstantRemediation("30min")

this might be a bit misleading, for example if this is something that cant be fixed by users. bug in the plugin.

**Comment by guwirth** [comment]
I'm also not sure, but others do it also: https://github.com/SonarCommunity/sonar-python/blob/master/python-checks/src/main/java/org/sonar/python/checks/ParsingErrorCheck.java
or see JavaScript plugin.

**Comment by jmecosta** [comment]
a bit more on this, current api requires all rules to define technical debt. so if we want those remove we need to take the rules out and moved them to the xml definition

**Comment by guwirth** [comment]
solved with #490
