### ISSUE TITLE
Sensors should not run during local analysis, incremental and preview

### ISSUE THREAD

**Issue by jmecosta** [wenns/sonar-cxx#478]

**Comment by guwirth** [comment]
Think this could also be fixed in **shouldExecuteOnProject(Project project)** with #550. 

@jmecosta Could you give some more background information please?
How can be detected if local, incremental and preview analysis active?

**Comment by jmecosta** [comment]
i will verify this and if not i can try to get the pr for this.. analysis type is passed as build argument:

http://www.sonarqube.org/analysis-vs-preview-vs-incremental-preview-in-sonarqube/

sonar.analysis.mode=preview
sonar.analysis.mode=incremental

**Comment by guwirth** [comment]
Ok. But what I still do not understand is why in this modes some sensors should be deactivated?

**Comment by jmecosta** [comment]
Not sure anymore, perhaps it was slowing down the analysis. For example
unit test sensor is heavy if it tries to parse source files.

I will double check with new version

**Comment by guwirth** [comment]
Maybe #550 solves your problem already. Without a report path in the project properties a sensor is no more called.

**Comment by jmecosta** [comment]
apparently there is not delays with latest version.

17:43:33.581 INFO  - Sensor CxxSquidSensor (done) | time=259712ms
17:43:33.581 INFO  - Sensor CxxRatsSensor
17:43:33.582 INFO  - Sensor CxxRatsSensor (done) | time=1ms
17:43:33.582 INFO  - Sensor CxxXunitSensor
17:43:33.582 INFO  - Sensor CxxXunitSensor (done) | time=0ms
17:43:33.582 INFO  - Sensor CxxCoverageSensor
17:43:53.578 INFO  - Sensor CxxCoverageSensor (done) | time=19996ms
17:43:53.579 INFO  - Sensor CxxCppCheckSensor
17:43:53.579 INFO  - Sensor CxxCppCheckSensor (done) | time=0ms
17:43:53.579 INFO  - Sensor CxxVeraxxSensor
17:43:53.579 INFO  - Sensor CxxVeraxxSensor (done) | time=0ms
17:43:53.579 INFO  - Sensor CxxValgrindSensor
17:43:53.579 INFO  - Sensor CxxValgrindSensor (done) | time=0ms
17:43:53.579 INFO  - Sensor CxxExternalRulesSensor
17:43:53.580 INFO  - Sensor CxxExternalRulesSensor (done) | time=1ms


closing. opening again if finding other issues

**Comment by Typz** [comment]
In general, it really depends on the sensor.
Analysis mode is useful for developers, to use sonarqube to check issues some changes before they are submitted.

So all slow/network sensors (e.g. list issues from bug tracker) should be disabled in these modes. Not sure how it directly affects the C++ plugin... Normally, dependency matrix computation should also be disabled in these modes.

On the other hand, the c++ plugin does not fully support this use case: normally in these modes, the runner will only request analysis of the modified files, and report only issues not present in server. This works fine when the analysis is performed directly by the plugin (e.g. Squid checks) but not so well when reports must be generated by some external tools, as these must be generated before running sonar, and don't know what files should actually be analyzed.

Ideally, to support these use case, the plugin should be enhanced to support running each tool to generate the reports... But that is a big paradigm change, and requires driving all tools as well as dealing with the "installation" (or discovery of installed path) of the tools on each computer.

**Comment by jmecosta** [comment]
if you use visual studio i fully support this paradigm. i reuse the information from the analysis to detect which files should be analysis and run all configured tools (cppcheck, rats, etc) and append the issues from the squid sensor with the tools. 

the time i added there: 259712ms is the squid sensor for a about 500K lines of c++ code. so its not terrible bad for a preview. and the dependency matrix runs in about 10 secs so not a big issue.

for incremental with a couple of files modified.... no issues either:

20:19:52.162 INFO  - Sensor CxxSquidSensor (done) | time=9630ms

**Comment by jmecosta** [comment]
thinking a bit better, likely this should be implemented so it clear we dont support this in local analysis modes.

Looking at #550 not sure if the coverage sensor should run

**Comment by jmecosta** [comment]
Closing since this does not affect times that much
