### ISSUE TITLE
How to upload a binary to a release?

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#481]
I'm not able to upload the jar file to the release. Getting always an error from github. Can someone help?

**Comment by jmecosta** [comment]
Is last upstream you want in the pre release?

**Comment by guwirth** [comment]
Doing it like described her: https://help.github.com/articles/creating-releases/. Everything is working fine except step 8: include binary files. Like to add the jar file but always getting an error message from the browser at the end of uploading. Tried it with IExplorer and Firefox.

**Comment by jmecosta** [comment]
just drag and drop works fine for me
https://github.com/wenns/sonar-cxx/releases/tag/cxx-0.9.3-pre-release

**Comment by guwirth** [comment]
Which browser / version of browser are you using?

**Comment by jmecosta** [comment]
Chrome windows 8.1

**Comment by guwirth** [comment]
Really strange. Can't upload a binary whether with IExplorer, Firefox, nor Chrome? Maybe a limitation of our company network. Will check this evening on another PC.

**Comment by jmecosta** [comment]
Yep sounds somethig like that

**Comment by guwirth** [comment]
CORS is disabled in our company network:
```
Cross-Origin Request Blocked:
The Same Origin Policy disallows reading the remote resource at
https://github-cloud.s3.amazonaws.com/.
This can be fixed by moving the resource to the same domain or enabling CORS.
```
