### ISSUE TITLE
v0.9.3-RC1

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#482]
Announcement of v0.9.3-RC1. This is a pre-release and should not be used in a productive environment. Please create a backup of your setup before using this version!

v0.9.3-RC1 is using 4.5.2 API and is compatible to SQ 4.5.2, 4.5.4, 5.0.1 and 5.1.

* [enhancements](https://github.com/wenns/sonar-cxx/issues?q=created%3A%3E2015-01-14+is%3Aclosed+label%3Aenhancement)
* [bugfixes](https://github.com/wenns/sonar-cxx/issues?q=created%3A%3E2015-01-14+is%3Aclosed+label%3Abug)
* [known issues](https://github.com/wenns/sonar-cxx/issues?utf8=%E2%9C%93&q=created%3A%3E2015-01-14+is%3Aopen+label%3Abug)

We like to start a beta test phase by 2015-04-26.
Please test the version and give us feedback.

Download: https://github.com/wenns/sonar-cxx/releases/tag/cxx-0.9.3-pre-release

**Comment by guwirth** [comment]
Please support us in extending our [Wiki](https://github.com/wenns/sonar-cxx/wiki). See [documentation request flag](https://github.com/wenns/sonar-cxx/issues?utf8=%E2%9C%93&q=label%3A%22docu+request%22) for enhancements which need some explanation.

 **The best feature is useless without an explanation how to use it!**

**Comment by guwirth** [comment]
No news are good news :-). There is very less feedback to RC1. Don't know if this is good or bad. Also many 'documentation request' are still open.

So don't know how to proceed:
1) release on Sunday as planned
2) create an RC2 for further testing (my favorite)

Please vote.

**Comment by jmecosta** [comment]
can we take the doc request from the ones missing done already

**Comment by guwirth** [comment]
Yes for sure. Please add a link to the Wiki page with the corresponding docu into the issue and remove the 'docu request' label.

**Comment by jmecosta** [comment]
i vote for release... ive did not found anything with latest that would stop me using the plugin. would only inlude #495 since since generally broken for mm projects.

the rest imo can be closed and reopened if needed. 

documentation from my side is done, likely most of the others a note in release notes?

**Comment by guwirth** [comment]
Hi together,

Release notes are ready to review: https://github.com/wenns/sonar-cxx/releases/tag/untagged-82c3e68fb0e70a73ca5b
* Please also vote: (1) RC2 or (2) RELEASE
* @wenns We are ready with 0.9.3. Please give also your go.

Regards,

**Comment by wenns** [comment]
Hi guys, 
I see you've been busy :)

> @wenns We are ready with 0.9.3. Please give also your go.
I'll try to give it a look tonight and write you then.

**Comment by jmecosta** [comment]
Seems very good, state very close to 1.0?

**Comment by wenns** [comment]
Hm. I cannot build master neither on Linux nor on Windows: The error message is:

```BASH
Cxx ............................................... SUCCESS [1.274s]
[INFO] Cxx :: Squid ...................................... SUCCESS [4.182s]
[INFO] Cxx :: Checks ..................................... SUCCESS [1.793s]
[INFO] Cxx :: Sonar Plugin ............................... FAILURE [2.439s]
[INFO] Cxx :: SSLR Toolkit ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.436s
[INFO] Finished at: Mon Apr 27 09:37:55 CEST 2015
[INFO] Final Memory: 23M/679M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.sonar:sonar-packaging-maven-plugin:1.12.1:sonar-plugin (default-sonar-plugin) on project sonar-cxx-plugin: Error assembling Sonar-plugin: null: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sonar-cxx-plugin
```

Am I doing something wrong?

**Comment by guwirth** [comment]
@wenns was the last update on trunk in pom file:

    <developer>
      <id>ametselaar</id>
    </developer>

Only id seems to be too less. But I have not more. I will undo it.

**Comment by guwirth** [comment]
Please update and rebase. At least on my system it is working again...
Sorry for the inconvenience..

**Comment by wenns** [comment]
Yep, better now. Another thing: I compared metrics for 2015.01.03 and current state and the've slighly worse now (coverage, issues / technical debt etc.). While thats not a major issue (the drops are not that big): maybe there is room for small improvements?

![screenshot from 2015-04-27 11 01 54](https://cloud.githubusercontent.com/assets/1336856/7344623/844a103a-eccd-11e4-8d9b-75411837462b.png)

**Comment by wenns** [comment]
The integration tests are running, which is cool. I wonder how to get coverage for them.

**Comment by guwirth** [comment]
Technical debt: see https://github.com/wenns/sonar-cxx/wiki/Upgrade-Instructions
Three main points from my point of view:
* Property sonar.cxx.coverage.forceZeroCoverage supports line, integration and overall coverage now. 
* Some of the rules has changed rule keys. Especially template rules are not activated by default. Please check listed rules below if they have the same state in your profile as before.
* External rules (other) does not support Sqale characteristics.

**Comment by guwirth** [comment]
> The integration tests are running, which is cool. I wonder how to get coverage for them.

We have to add the coverage reports.

**Comment by guwirth** [comment]
@wenns: The working day is drawing to a close :-).
What is your decision (1) RC2 or (2) RELEASE?

**Comment by wenns** [comment]
I vote for a release.

**Comment by guwirth** [comment]
I vote also for release.

**Comment by Bertk** [comment]
+1 for release

**Comment by guwirth** [comment]
@wenns or @jmecosta can one of you upload the binaries and release it please. (new build without -SNAPSHOT)
All other things are done: https://github.com/wenns/sonar-cxx/releases/tag/untagged-3eb4ef00604b2c8ead17
Thx

**Comment by jmecosta** [comment]
done

**Comment by guwirth** [comment]
@jmecosta: Thx. Could you also upload the sslr toolkit please.

**Comment by jmecosta** [comment]
Yep of course.

**Comment by jmecosta** [comment]
@guwirth its done now

**Comment by guwirth** [comment]
@jmecosta Thx
