### ISSUE TITLE
PC-Lint import stops with Exception

### ISSUE THREAD

**Issue by chrissy25** [wenns/sonar-cxx#488]
I try to import a PC-Lint report into SonarQube and it is working very fine but only until some points. I can see how the plugin is remapping the MISRA rules to the internal MISRA rules. But it hangs everytime on the same point and throws an exception: 

ERROR: Caused by: Cannot feed the data into sonar, details: 'java.lang.IllegalStateException: No match found'
ERROR: Caused by: No match found

What is this error message about? When is the plugin throwing this exception?

**Comment by chrissy25** [comment]
Okay, I think I have found the problem. It is a problem with pattern matching in the method "mapMisraRulesToUniqueSonarRules". There is no check if the pattern matching was successful and even when it was not successful the method tries to use the first match.

The pattern, which is used to find find the MISRA rule key is:
"Rule\\x20(\\d{1,2}.\\d{1,2}|\\d{1,2}-\\d{1,2}-\\d{1,2}),"


But for the rule "524": 
Loss of precision (assignment) (float to unsigned int) [MISRA 2004 Rule 10.1]


This is not working, as there is no comma after the rule key. But the method still wants to use the first match, which is not there and then this exception will be thrown.

Is the comma in the pattern really needed, or can it be removed? I think without the comma it should also work  =)

**Comment by guwirth** [comment]
Could you please add an XML example of your problem
```XML
<result>
   <issue ... />
</result>
```

> The pattern, which is used to find find the MISRA rule key is: "Rule\x20(\d{1,2}.\d{1,2}|\d{1,2}-\d{1,2}-\d{1,2}),"

https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/pclint/CxxPCLintSensor.java

There are two points:

> There is no check if the pattern matching was successful and even when it was not successful the method tries to use the first match.

regex should not crash: handle error conditions

> Is the comma in the pattern really needed, or can it be removed?

Is someone familiar with the pc-lint format and can answer this question (@Bertk)? Looking in the unit tests they have all a comma: https://github.com/wenns/sonar-cxx/tree/master/sonar-cxx-plugin/src/test/resources/org/sonar/plugins/cxx/reports-project/pclint-reports

**Comment by chrissy25** [comment]
Please find here the XML example, where the description do not contain a comma and the exception will be thrown:

```XML
<result>
    <issue file ="somefile.c" line = "141" number = "524" desc = "Loss of precision (assignment) (float to unsigned int) [MISRA 2004 Rule 10.1]"/>
</result>
```

**Comment by Bertk** [comment]
Please see the test resource https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/test/resources/org/sonar/plugins/cxx/reports-project/pclint-reports/pclint-result-MISRA2004-SAMPLE.xml. The current parser consumes PC-lint Messages 960, 961, 1960, 1963 and maps the issue to an individual rule.

Which version of PC-lint are you using? 
Please use *au-misra-cpp.lnt* to enable the special MISRA messages 1960, 1963.

The latest PC-lint Version 9.0l supports a new syntax for MISRA messages and now individual messages will be created ('*au-misra-cpp-alt.lnt*'). Please check http://www.gimpel.com/html/pub90/msg.txt and section 'What's New in the 9.00L Patch' in http://www.gimpel.com/html/pub90/read90.txt.

If the backward compatibility is not working, we will consider supporting only the new syntax for MISRA messages. This is a breaking change for the PC-lint MISRA rules and every user has to adapt the SonarQube C++ profile.

**Comment by chrissy25** [comment]
We are using PC-Lint 9.0k and *au-misra2.lnt*  to check MISRA 2004 rules.

Is this comma in the regex really needed, or can it be removed? I would expect that this can also be removed, and with this the regex would be compatible to more rules.

And also the error handling is needed, so that Sonar will not stop the analyzing.

**Comment by guwirth** [comment]
> Is this comma in the regex really needed, or can it be removed?

old:
```
desc = "Both sides have side effects [MISRA 2004 Rule 1.2, required]"
desc = "Violates MISRA 2004 Required Rule 8.1, no prototype for function 'do_report_status' "
```
new:
```
desc = "Loss of precision (assignment) (float to unsigned int) [MISRA 2004 Rule 10.1]"
```
What could work is comma or bracket at the end?
```
Rule\x20(\d{1,2}.\d{1,2}|\d{1,2}-\d{1,2}-\d{1,2})(,|\])
```
