### ISSUE TITLE
[Parser Error ] "::" expected but ">>" [BW_RSHIFT] found

### ISSUE THREAD

**Issue by wenns** [wenns/sonar-cxx#49]
The relevant thread where ambiguity is described:
http://sonar.15.x6.nabble.com/sonar-dev-SSLR-for-C-community-Plugin-td5009119.html

**Comment by ametselaar** [comment]
In https://github.com/ametselaar/sonar-cxx/tree/nested-templates I have solved the issue for nested templateId's by allowing to close two template argument lists with a single '>>'. C++ style casts are not supported (yet).

**Comment by jmecosta** [comment]
great, i gave a try... and results are much better... seems there is a case that fails

template<class T, class Compare = std::less<T>>

anyway, hope you dont mind. ive rebase you last commit against current upstream: https://github.com/wenns/sonar-cxx/pull/378

**Comment by guwirth** [comment]
What is the state of this?

**Comment by jmecosta** [comment]
#400 has been updated with latest commit
