### ISSUE TITLE
CppCheck sensor shall support project findings

### ISSUE THREAD

**Issue by Bertk** [wenns/sonar-cxx#491]
The following CppCheck (1.68)  finding is not handled correctly:
```
        <error id="unmatchedSuppression" severity="information" msg="Unmatched suppression: unusedFunction" verbose="Unmatched suppression: unusedFunction">
            <location file="*" line="0"/>
        </error>

```
Instead of adding a finding in SonarQube DB an error message is written to log file:
```
11:23:37.684 ERROR - path normalizing of 'C:\TFS_Server\Server\common\Source\converterLib\.\*' failed: 'java.io.IOException: Invalid argument'

**Comment by guwirth** [comment]
In your example is```file="*"```. What would you expect in such a case?

**Comment by Bertk** [comment]
The CppCheck sensor already supports issues on project level and this kind of message shall be handled similarly. The combination of 'file="*"' and 'line="0"' can be used to identify this case and this information shall be dropped. Without these attributes the issue will be assigned on project level.

**Comment by guwirth** [comment]
I think is no problem to add this special case (project issue)

Would only look for file==* 
   set file to null
   set line to zero 
in this case.

**Comment by Bertk** [comment]
Yes, this should work.

**Comment by Bertk** [comment]
Sorry, but we forgot a small update for the Cpp rule repository:
```
09:57:04.639 ERROR - Could not add the issue, details: 'The rule 'cppcheck:unmatchedSuppression' does not exist.'
```

**Comment by guwirth** [comment]
Missing rule support is a different issue. 
Close this and open #502 instead.
