### ISSUE TITLE
Problem with Travis

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#494]
Travis build breaks randomly.

**Comment by guwirth** [comment]
To all Travis artists. Any idea what that could be?
* the code did not change anything on the plugin
* the PR was not changing anything on the integration tests
* download, installation, build and unit tests successful

One example for a failing build: ValueError: No JSON object could be decoded
https://travis-ci.org/wenns/sonar-cxx/jobs/59692337
```
Feature: Importing coverage data
As a SonarQube user
I want to import my coverage metric values into SonarQube
In order to be able to use relevant SonarQube features
Scenario: Importing coverage reports 
Given the project "coverage_project"
Given the project "coverage_project"
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1456, in run
match.run(runner.context)
File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1903, in run
self.func(context, *args, **kwargs)
File "integration-tests/features/steps/test_execution_statistics.py", line 43, in step_impl
profiles = json.loads(response.text).get("qualityprofiles", None)
File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jmecosta** [comment]
Can we see build history by agent, perhaps one of the agents contains a
different version of python. ? Anyway, its probably worth to send email to
Travis team to check this

**Comment by jmecosta** [comment]
Ive see also 255 error codes, in teamcity we usually got those if running
32 bit tools on 64 bit machines. But those are usually quite random. But it
seems the quality of Travis as decrease a bit lately, before things run
much more smoothly

**Comment by guwirth** [comment]
Sent an issue report to Travis.

**Comment by guwirth** [comment]
**Travis-Support:** *"Es scheint mir als sei der fehlschlagende Test nicht deterministisch (dieser tested, zumindest so wie ich es von den Logs verstehe, dass der Warnhinweis "WARNING Journal flush operation took 6,146ms last 8 cycles average is 768ms" nicht erscheint). Es könnte sein, dass die Schwankungen in der IO-Preformance durch die zu Grunde liegende Virtualisierung verursacht werden. Unter Umständen würde ein Wechsel auf unsere containerbasierte Infrastruktur hier Abhilfe schaffen, ich bin mir aber nicht sicher ob man die `pip` befehle dort ohne `sudo` ausführen kann.*

*Vielleicht wäre eine einfachere Lösung den Test anzupassen.*

*Als ein kleiner Hinweis anbei: Unser Supportteam ist leider ausschließlich in der Lage auf Englische Anfragen und ausschließlich in Englisch zu antworten, Support auf Deutsch ist daher nur eingeschränkt möglich, abhängig von der Verfügbarkeit anderer Mitarbeiter. Ich bitte um Ihr Verständnis."*

**Comment by guwirth** [comment]
Are there any timeout measurements or performance measurements in our tests?

**Comment by jmecosta** [comment]
Not that am aware

**Comment by guwirth** [comment]
Seems to work again.
