### ISSUE TITLE
VCCppBuildLogParser - resolve include folders fails for relative path

### ISSUE THREAD

**Issue by Bertk** [wenns/sonar-cxx#495]
There might be an issue with the baseDir for the multi module projects and relative paths e.g. "/I..\..\..\boost\include". I use the sonar-visual-studio bootstrapper and the baseDir of the solution is used instead of the baseDir of the module.

A warning message like the following will be logged:
```
19:04:09.853 WARN  - the include root 'C:\boost\include' doesn't exist
```
My VC log file does not have "from Project" and this seams to be the reason. Anyway the vcxproj file is located in baseDir of the module and potential fix could look like this:
```
currentProjectPath = Paths.get(".");
// should be replaced by
currentProjectPath = fs.baseDir().getPath();
```
@jmecosta What do you think?

**Comment by jmecosta** [comment]
Yes that better solution, did not even remember that basedir is available.
Do i prepare pull request or you?

**Comment by Bertk** [comment]
I think you are faster.

**Comment by jmecosta** [comment]
Ok try to do tomorrow

**Comment by jmecosta** [comment]
#497
