### ISSUE TITLE
Improve VCCppBuildLogParser handling of _MSC_FULL_VER

### ISSUE THREAD

**Issue by Bertk** [wenns/sonar-cxx#501]
We use boost and the _MSC_FULL_VER macro is uded to identify C++ features (see boost/config/compiler/visualc.hpp).

Today the default setting is ```AddMacro("_MSC_FULL_VER=150020706", fileElement)``` and a better way is to use ```private enum VSVersion { V100, V110, V120, V140 } ``` and set the versions numbers accordingly.

**Comment by jmecosta** [comment]
Yes this is good idea, anyway there are some default macros also in other
parts of the plugin that should be reviewed. Is this needed for this
version?

**Comment by Bertk** [comment]
@jmecosta: Please review PR #537 and send your feedback. I did not introduce the enum ...
This feature is helpful for the VC++ Compiler and I feel we should have it also for GCC. Unfortunately I do not use GCC.

**Comment by guwirth** [comment]
@Bertk and @jmecosta can we close this?

**Comment by jmecosta** [comment]
Think so

**Comment by Bertk** [comment]
Solution is merged.
