### ISSUE TITLE
Wiki: Dealing with compiler specific code peaces

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#504]
Content of page 'Dealing with compiler specific code peaces' is missing. Maybe one of you has a copy?

**Comment by jmecosta** [comment]
I can add mention there to the buildlog parser, ive added that in a
different place

**Comment by jmecosta** [comment]
not sure totally what you refer, but added a 8) step to that list to mention the buildlog...

**Comment by guwirth** [comment]
The wiki page https://github.com/wenns/sonar-cxx/wiki/Dealing-with-compiler-specific-code-peaces is empty but I remember I wrote a description. So don't know what happened? is there also a history for the whole wiki to look why the content disappeared?

**Comment by jmecosta** [comment]
issues is that there are 2 pages with same name

yours:
https://github.com/wenns/sonar-cxx/wiki/Dealing-with-compiler-specific-code-peaces

and the one that has content:
https://github.com/wenns/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces

pieces vs peaces

**Comment by guwirth** [comment]
Thx. Seems someone fixed the typo in the caption which led to the broken link.
