### ISSUE TITLE
Complete C++11 support

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#507]
For examples see http://en.cppreference.com/w/cpp/language

**Comment by Bertk** [comment]
Please see some C++11/14 examples which are available on cppreference.com 
(aacbd96e552c642cf56b2af2cfed31ca1bf6690e).
The following examples create parser errors which are marked with a ToDo comment:
* decl-type.cc
* parameter-pack-sizeof.cc
* parameter-pack.cc
* user-defined-literals.cc
* integer-sequence.cc (C++14)

**Comment by guwirth** [comment]
I think there are many points open and we need some help.
Who can help us to extend the parser?

**Comment by guwirth** [comment]
Todo:
* https://github.com/wenns/sonar-cxx/blob/master/cxx-squid/src/test/resources/parser/own/C%2B%2B11/decl-type.cc
* https://github.com/wenns/sonar-cxx/blob/master/cxx-squid/src/test/resources/parser/own/C%2B%2B11/parameter-pack-sizeof.cc
* https://github.com/wenns/sonar-cxx/blob/master/cxx-squid/src/test/resources/parser/own/C%2B%2B11/parameter-pack.cc
* https://github.com/wenns/sonar-cxx/blob/master/cxx-squid/src/test/resources/parser/own/C%2B%2B11/user-defined-literals.cc

**Comment by guwirth** [comment]
* decl-type.cc => already solved
* parameter-pack-sizeof.cc => already solved
* parameter-pack.cc => variadic template: unpack of parameter packs not supported
https://github.com/wenns/sonar-cxx/blob/master/cxx-squid/src/test/resources/parser/own/C%2B%2B11/parameter-pack.cc
* user-defined-literals.cc => preprocessor problem: has to support user defined literals
https://github.com/wenns/sonar-cxx/blob/master/cxx-squid/src/test/resources/parser/own/C%2B%2B11/user-defined-literals.cc

**Comment by guwirth** [comment]
known issues #560, #561, #562, #563, #564

**Comment by guwirth** [comment]
All C++11 features should work now. At least the straight forward use cases are tested. I close this issue. For still existing parsing problems we should create new specific issues,
