### ISSUE TITLE
AST parser error 'for (const std::string &i : v)'

### ISSUE THREAD

**Issue by Bertk** [wenns/sonar-cxx#511]
The following code creates parser errors (line 11 and line 23).
```
// Win32Project1.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"


int _tmain(int argc, _TCHAR* argv[])
{
  std::vector<std::string> v = { "test1", "test2", "test3" };

  for (const std::string &i : v) // access by const reference
    std::cout << i.c_str() << ' ';
  std::cout << '\n';

  for (auto i : v) // access by value, the type of i is int
    std::cout << i.c_str() << ' ';
  std::cout << '\n';

  for (auto&& i : v) // access by reference, the type of i is int&
    std::cout << i.c_str() << ' ';
  std::cout << '\n';

  for (std::string n : {"test1", "test2", "test3"}) // the initializer may be a braced-init-list
    std::cout << n.c_str() << ' ';
  std::cout << '\n';

	return 0;
}
```

**Comment by Benoitlz** [comment]
The 'const' seems to be a problem ... here some more examples:
16:49:41.576 ERROR - Parse error at line 47 column 31:

   37: ::GetMaxTime()
   38:     {
   39:         return maxTime;
   40:     }
   41: 
   42:     void FilterMinMaxTime::SetMaxTime(double maxTime)
   43:     {
   44:         FilterMinMaxTime::maxTime = maxTime;
   45:     }
   46: 
  -->      void FilterMinMaxTime::Run(const ManagedMemoryVector<DataPoint>& sourceData, ManagedMemoryVector<DataPoint>& filteredData)
   48:     {
   49: 
   50:         filteredData.clear();
   51:         for (const DataPoint& dataPoint : sourceData

16:49:46.451 ERROR - Parse error at line 70 column 38:

   60: ::GetValueOffset()
   61:     {
   62:         return valueOffset;
   63:     }
   64: 
   65:     void FilterTranslateAndScale::SetValueOffset(double valueOffset)
   66:     {
   67:         FilterTranslateAndScale::valueOffset = valueOffset;
   68:     }
   69: 
  -->      void FilterTranslateAndScale::Run(const ManagedMemoryVector<DataPoint>& sourceData, ManagedMemoryVector<DataPoint>& filteredData)
   71:     {
   72:         filteredData.clear();
   73:         for (const DataPoint& dataPoint : sourceData

16:50:39.680 ERROR - Parse error at line 1428 column 23:

 1421: curConcValues[iFluid - 1]
 1422:                 = float(simuConcentration[iSection][iFluid][iDepth]);
 1423:             }
 1424:         }
 1425:     }
 1426: 
 1427:     void DisplacementSimulatorSlice::FilterPumpingSchedule(
  -->          PumpingSchedule& pumpingSchedule,
 1429:         const Fluids& fluids)
 1430:     {
 1431:         const auto& fluidsMap = fluids.fluids;
 1432:         auto hasFluidID = [&fluidsMap] (int fluidId) {

**Comment by Benoitlz** [comment]
Other examples of the 'for()' parsing error:
12:57:39.455 ERROR - Parse error at line 33 column 4:

   26: Pipe.append();
   27:     m_xmlFluidPlacement.Annulus.append();
   28:     m_xmlFluidPlacement.Rathole.append();
   29: }
   30: 
   31: XMLFluidPlacement::~XMLFluidPlacement()
   32: {
  -->      for (XMLFluidPlacementEntry* entry: m_pipeFluidPlacementEntries->entries)
   34:     {
   35:         delete entry;
   36:     }
   37:     delete m_pipeFluidPlacementEntries;
   38:     for (XMLFluidPlacementEntry* entry: m_annulusFluidPlacementEntries->entries)
   39:     {
   40:         delete

13:08:10.037 ERROR - Parse error at line 29 column 8:

   15: WCS
   16: {
   17: namespace Simulator
   18: {
   19: namespace Application
   20: {
   21: namespace NumericalCompare
   22: {
   23:     CurveComparerCollection::CurveComparerCollection() : m_method(AND)
   24:     {
   25:     }
   26: 
   27:     CurveComparerCollection::~CurveComparerCollection()
   28:     {
  -->          for (ICurveComparer* curveComparer : m_curveComparers)
   30:             delete curveComparer;
   31:     }

13:43:19.584 ERROR - Parse error at line 21 column 4:

   15: namespace FADEPlugin {
   16: 
   17: Fluids::Fluids() {}
   18: 
   19: Fluids::~Fluids()
   20: {
  -->      for (Fluid* fluid: m_fluids)
   22:     {
   23:         delete fluid;
   24:     }
   25: }
   26:

**Comment by Bertk** [comment]
The parser processes this file without errors and the ```const``` specifier does not create an error. I guess the ```std::string``` or any other user type makes the parser fail.

```  
#include <atlstr.h>
#include <iostream>
#include <string>
#include <vector>

void test1(void)
{
  std::vector<int> v = { 0, 1, 2, 3, 4, 5 };

  for (const int &i : v) // access by const reference
    std::cout << i << ' ';
  std::cout << '\n';
}

void test2(void)
{
  std::vector<std::string> v = { "test1", "test2", "test3" };

  for (const auto &i : v) // access by const reference
    std::cout << i.c_str() << ' ';
  std::cout << '\n';

  //for (const std::string &i : v) // access by const reference
  //  std::cout << i.c_str() << ' ';
  //std::cout << '\n';

  for (auto i : v) // access by value, the type of i is int
    std::cout << i.c_str() << ' ';
  std::cout << '\n';

  for (auto&& i : v) // access by reference, the type of i is int&
    std::cout << i.c_str() << ' ';
  std::cout << '\n';

  //for (std::string n : {"test1", "test2", "test3"}) // the initializer may be a braced-init-list
  //  std::cout << n.c_str() << ' ';
  //std::cout << '\n';
}


int _tmain(int argc, _TCHAR* argv[])
{
  test1();
  test2();
  
  return 0;
}

```

**Comment by Bertk** [comment]
This parser rule *forrangeDeclSpecifierSeq* fails and I found one ToDo comment in *simpleTypeSpecifier* which should be considered but I am not sure whether this fixes the issue (more Information for *simple type specifier* is available here http://en.cppreference.com/w/cpp/language/declarations). 
```
    b.rule(simpleTypeSpecifier).is(
      b.firstOf(
        "char", "char16_t", "char32_t", "wchar_t", "bool", "short", "int", "long", "signed", "unsigned", "float", "double", "void", "auto",
        decltypeSpecifier,
        b.sequence(nestedNameSpecifier, CxxKeyword.TEMPLATE, simpleTemplateId),

            // TODO: the "::"-Alternative to nested-name-specifier is because of need to parse
            // stuff like "void foo(::A a);". Figure out if there is another way

        b.sequence(b.optional(b.firstOf(nestedNameSpecifier,"::")), typeName)
        )
      );
```
The unit test *iterationStatement_reallife()* should be enhanced 
```
  @Test
  public void iterationStatement_reallife() {
    p.setRootRule(g.rule(CxxGrammarImpl.iterationStatement));

    assertThat(p).matches("for (int i=1; i<=9; ++i) { coll.push_back(i); }");
    assertThat(p).matches("for (const auto &i : v) { std::cout << i.c_str() << ' '; }");
// ToDo: Make this work
//    assertThat(p).matches("for (const std::string &i : v) { std::cout << i.c_str() << ' '; }");
//    assertThat(p).matches("for (XMLFluidPlacementEntry* entry: m_pipeFluidPlacementEntries->entries) {delete entry;}");
//    assertThat(p).matches("for (ICurveComparer* curveComparer : m_curveComparers) delete curveComparer;");
  }
```

**Comment by guwirth** [comment]
@Bertk have you tried to analyze the problem in the sslr toolkit? Load the code snippet into the tool and see what the parser is doing.

Think the :: is a problem (workaround) with the global namespace.

**Comment by guwirth** [comment]
Played around a little bit:
```
for(mytype i : v);
```
is also not working.

**forRangeDeclaration** is wrong, must be something like *"simpleDeclSpecifierSeq, declarator"*. Will have a look tomorrow.
