### ISSUE TITLE
Unexpected EOF exception when loading rules via sonar.cxx.other.rules property

### ISSUE THREAD

**Issue by hfufu** [wenns/sonar-cxx#514]
I was doing some automated installation and setup of sonar and trying to load the "other" rules https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/resources/external/intel_inspector_rules.xml into sonar from the sonar.cxx.other.rules property. However, when sonar started, the following error occurs in the log:
2015.05.11 07:16:39 INFO  web[org.sonar.INFO]  Register rules...
2015.05.11 07:16:42 INFO  web[CxxPlugin]  Cannot Load XML '[com.ctc.wstx.exc.WstxLazyException] Unexpected EOF in CDATA section
 at [row,col {unknown-source}]: [1,1392]'
2015.05.11 07:16:42 INFO  web[CxxPlugin]  Cannot Load XML 'XML is not valid'

The same file can be loaded successfully from the Web UI configuration page.

The error location of the xml is actually a "," char. If I remove all the comma in the property string, it can load successfully. Following the code, it looks like the problem is from the use of settings.getStringArray(RULES_KEY) in CxxExternalRuleRepository.java.  

The getStringArrary input is a regular string and does not assume XML or CDATA, and use the comma as separator to break a string into array of string value. This cause the input XML string split unexpectedly when there is comma in the CDATA.

**Comment by jmecosta** [comment]
What versions are you using, ive been using this xml for along time without
any issues.

**Comment by hfufu** [comment]
C++ (Community) [cxx]	0.9.2
Sonarqube 4.5.2
Please note that the problem does not appear if loading the rules from Web UI "General Setting" page. 

The problem appears only when specifying the rules as a sonar.cxx.other.rules property value in the sonar.properties file.

**Comment by jmecosta** [comment]
Thats not supported. The rules must be set in the we ui. Because they need
to be available during server restart.
