### ISSUE TITLE
"Unit Tests Coverage" and "Integration Tests Coverage" shows different coverage result with the same input

### ISSUE THREAD

**Issue by tim-yeung** [wenns/sonar-cxx#515]
The subset of sonar.properties which I use:
sonar.cxx.coverage.reportPath=sonar.cov.xml
sonar.cxx.coverage.itReportPath=sonar.cov.xml

After the sonar project is updated with the coverage result in sonar.cov.xml, I am able to see the coverage result under "Unit Tests Coverage" and "Integration Tests Coverage". BUT THE COVERAGE PERCENTAGE IS DIFFERENT, even the same sonar.cov.xml is used.

The coverage percentage in "Unit Tests Coverage" is lower than the coverage percentage in "Integration Tests Coverage". 

After some tracing, it seems "Unit Tests Coverage" contains files that have 0% coverage, but are not present in sonar.cov.xml.

Is this a bug? I don't expect files which are not present in sonar.cov.xml to be counted as 0% coverage.

**Comment by guwirth** [comment]
Which version you are using?

**Comment by tim-yeung** [comment]
I am using 0.9.2.

Actually, I found out this is fixed in 0.9.3, because of the update in forceZeroCoverage on integration and overall coverage.

Thank you for your fast response!
