### ISSUE TITLE
sonar-cxx 0.9.3 doesn't show technical debt (issues) with sonar 4.5.x

### ISSUE THREAD

**Issue by Benoitlz** [wenns/sonar-cxx#519]
sonar-cxx 0.9.3 doesn't show technical debt (issues) with sonar 4.5.x analyzing cpp code.
My initial environment was Java 7, Sonar 4.5.2,  sonar-cxx 0.9.2 is which I see the "Technical Debt" expressed in days.
I moved the environment to Java 8, Sonar 4.5.4,  sonar-cxx 0.9.3 no "Technical Debt" displayed.
In this environment, if I put back sonar-cxx 0.9.2, run sonar-runner again, "Technical Debt" is displayed again.
Then in this environment, if I revert to sonar-cxx 0.9.3, run sonar-runner again, "Technical Debt" is NOT displayed.
I read issue https://github.com/wenns/sonar-cxx/issues/464. I see no difference in the sonar log file between 0.9.2 and 0.9.3.
Looking at http://docs.sonarqube.org/display/SONAR/Technical+Debt, I'm not sure that issues are not taken in account anymore (first line, third paragraph). All the Technical Debt in my projects comes from issues reported by Cppcheck.
Did I miss something or is something missing in 0.9.3 ?

**Comment by jmecosta** [comment]
What issues are reported by the analysis?

**Comment by Benoitlz** [comment]
Thanks for your time!
I'm doing the tests with this issue: "Possible null pointer dereference" classified "major" (35 times)

**Comment by jmecosta** [comment]
cppcheck:nullPointer is not defined in sqale model. see here: https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/resources/com/sonar/sqale/cxx-model.xml

will be added for version 0.9.4 

you can try with other rules, there should be debt

**Comment by Benoitlz** [comment]
I extended my tests, still no Technical Debt computed. I have now the following issues:
- Member variable is not initialized in the constructor
- Buffer access out-of-bounds 
- Possible null pointer dereference 
- Wrong number of parameters given to printf()  
- Dereferencing variable after it is deallocated / released   
- Memory is freed twice  
- Memory leak  

By the way in cxx-model.xml link above, I see nullPointer, memleak, doubleFree ...

**Comment by jmecosta** [comment]
Ok that's odd, by any way did you mess up with database in past?

**Comment by Benoitlz** [comment]
I'm not sure what you mean by 'mess-up' ... I'm using mssql server, actually backed up my production instance and restored it on my test PC. 
I have tried to change some of the Parameters in the SonarQube Admin settings -> Technical Debt parameter.
What still surprises me is that yesterday (which is after all the above), just by switching the plugin from 0.9.3 to 0.9.2, I got the Technical Debt displayed back ...

**Comment by jmecosta** [comment]
How are you changing those debt parameters? Do you have the commercial
sqale plugin?

**Comment by jmecosta** [comment]
And can you install in a clean database. To rule out the analysis part

**Comment by Benoitlz** [comment]
No I don't have the commercial sqale plugin.
SonarQube Admin -> Settings -> Technical Debt -> Language specific parameter -> I added "CPP, 20, Lines of code", as well as Number of Working hours in  a day: 8. Pls note that I've done all this after 0.9.3 failed to display debt and before my switches back and forth with 0.9.2

Today I used the "Provisionning" to remove all projects. Then I also deleted all databases using a script in SQL Server ... Was that enough? I'm not sure as the above "CPP, 20, Lines of code" did not go away!

Anyway after this still no Technical Debt ... Then I move to SonarQube 5.1, no change!

**Comment by jmecosta** [comment]
I have not check this setting in the advance properties. But did you try
with a default database so without touching any settings. I would start
with the default database h2 run a analysis there. It should produce debt.

By the way what does this mean

CPP,20,lines of code

**Comment by jmecosta** [comment]
CPP if this is the language of the plugin ours is c++, do you have the c++
paid plugin installed by any chance?

**Comment by Benoitlz** [comment]
No I don't have the  c++ paid plugin.
May be I should try c++,lines of code ? (I'm not sure how this works [we had good debt without touching this and 0.9.2], but assumed that for an issue that appeared in one line of code, it would add 30 minutes to the technical debt ).

Do you mean I should switch the database driver to the default one (not SQL Server) ?

**Comment by jmecosta** [comment]
Yep but leave those settings untouched

**Comment by Benoitlz** [comment]
Tried with the default database (just switched in the config files, then analyze) ... no Debt Computed!
There are 36 Major issues (cppcheck nullPointer and memleak).

**Comment by jmecosta** [comment]
both do not have debt associated with them.

![image](https://cloud.githubusercontent.com/assets/1041352/7882863/642ec190-061a-11e5-9bce-cf12110151e0.png)

other show like this:
![image](https://cloud.githubusercontent.com/assets/1041352/7882889/9d90c730-061a-11e5-9d41-354a5f4723ff.png)

and after checking some of my chars i also notice that those have been lost... i will investigate on my side,,,, this seems a major regression

**Comment by jmecosta** [comment]
@Benoitlz i found the problem: can you confirm if this is working: https://bitbucket.org/jorge_costa/pluginsrepository/downloads/sonar-cxx-plugin-0.9.4-SNAPSHOT.jar

this is a big regression, @guwirth i think we need to release a bugfix release becasue all the sqale definitions are gone in new version.

reason is that core apparently does not read any more the definitions, instead we have to load them ourselfs. #521

**Comment by guwirth** [comment]
@jmecosta Is this closed with #521 ?

**Comment by jmecosta** [comment]
Lacks confirmation

**Comment by Benoitlz** [comment]
Thanks for working on this issue.
Sorry, but the link 0.9.4-SNAPSHOT.jar does not work for me (looks like bitbucket.org is blocked by my organization).
I will try from home tonight.

Benoit Lanthemann

**Comment by vic-trouble** [comment]
Hi

I'm having the same problem as @Benoitlz described and in my case installing the 0.9.4 preview helped technical debt to appear (I had to re-scan the project). 

Thanks

Vic

**Comment by Benoitlz** [comment]
0.9.4-SNAPSHOT.jar solves the problem of Technical Debt. t has now the same value as 0.9.3.
I tested with SonarQube 5.1, default and MSSQL databases.
Thanks for your help!
