### ISSUE TITLE
AST parser error - namespace alias '::TimerBase'

### ISSUE THREAD

**Issue by Bertk** [wenns/sonar-cxx#526]
Parser fails if a namespace alias (global namespace) is used (works with VC 12.0/14.0).

```
using TimerBase = boost::timer::auto_cpu_timer;
// removing '::' from '::TimerBase' does not create the C++ parser failure 
class  MyTimer : public ::TimerBase
{
public:
    MyTimer(const std::wstring& strName,
             const std::wstring& strMessage);
    ~MyTimer();
private:
// some more

};
```

**Comment by guwirth** [comment]
Think the parser don't know something from namespace alias (at least at the usage). Error should also occur with 'class  MyTimer : public ::TimerBase' alone? Can you verify this please?

**Comment by Bertk** [comment]
I fixed the first problem but this is not a complete fix for this issue. The *'class MyTimer : public ::TimerBase'* still creates a parser failure. 

```
 
  -->  class MyTimer : public ::TimerBase;EOF

	at org.sonar.sslr.internal.vm.Machine.parse(Machine.java:74)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:87)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:72)

```

**Comment by Bertk** [comment]
This works :innocent:
```
class MyTimer : public ::TimerBase {};
```

**Comment by guwirth** [comment]
@Bertk Should we close this or keep it open?

**Comment by Bertk** [comment]
We can close this issue - solution 08d5d6c is merged.
