### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by Phyks** [wenns/sonar-cxx#530]
Hi,

I have a parser error in sonar-cxx on the following code:
```
11:19:08.255 ERROR - Parse error at line 28 column 22:

   26: namespace udpserver
   27: {
  -->   UDPServer::UDPServer(const ty::int32_t port)
   29:   : port_(port),
   30:     sock_(0)
   31:  {
   32:
   33:   sock_ = socket(2      , 2         , 0);
   34:
   35:   if (
```

Last line is `if(-1 == sock_)`. Everything compiles fine under gcc and this code should be correct.

Thanks

**Comment by guwirth** [comment]
Which version are you using? 0.9.3 or 0.9.4?

**Comment by Phyks** [comment]
0.9.4 pre-release, cf https://github.com/wenns/sonar-cxx/issues/468.

**Comment by guwirth** [comment]
Not reproducible using (tested with SSLR:Cxx:Toolkit):
```C++
namespace udpserver
{
UDPServer::UDPServer(const ty::int32_t port) : port_(port), sock_(0)
{
    sock_ = socket(1,2,3);
    if(-1==sock_)
    {
       ;
    }
}
} // namespace
```
@Phyks Please try to provide a code snippet where problem is reproducible.

**Comment by Phyks** [comment]
@guwirth My bad, the parse error reported line is not the right one. It is due to a
```c++
struct sockaddr_in serverAddr;
serverAddr.sin_port = htons(port);
```

which is few lines below.

**Comment by guwirth** [comment]
Still not reproducible (tested with SSLR:Cxx:Toolkit 0.9.4 PR):

```C++
namespace udpserver {
   UDPServer::UDPServer(const ty::int32_t port) : port_(port), sock_(0)
    {
       sock_ = socket(1,2,3);
       if(-1==sock_)
       {
           struct sockaddr_in serverAddr;
           serverAddr.sin_port = htons(port);
       }
    }
} // namespace
```

@Phyks Please test yourself with SSLR:Cxx:Toolkit.

**Comment by Phyks** [comment]
@guwirth I tested with SSLR:Cxx:Toolkit and cannot reproduce the issue. However, the issue is still here when analyzing the whole project in Sonar with version 0.9.4-RC1.

**Comment by guwirth** [comment]
Is character encoding of the file ok?
Maybe a preprozessor issue?
...

**Comment by Phyks** [comment]
Character encoding is ok. My file compiles fine and I do not have any other issue with it. Plus preprocessor directives are supposed to be the same for all my files, and this file should not be handled differently than any other.

**Comment by guwirth** [comment]
@Phyks I'm sorry. Think we can't help you as long there is not a sample to reproduce the issue.

**Comment by Phyks** [comment]
Ok. I am off for a few weeks, I will try to debug a minimalistic working example as soon as possible. Thanks for your help!

**Comment by guwirth** [comment]
I'm closing this issue. Please re-open if still a problem.
