### ISSUE TITLE
Allow inverting/negating file and line RegEx rules

### ISSUE THREAD

**Issue by j-ulrich** [wenns/sonar-cxx#534]
Often it is impossible or very hard to detect files/lines which do **not** contain a certain pattern using regular expressions while it is easy to match the files/lines which do contain the pattern.

Therefore, it would be great if the File RegEx rule and Line RegEx rule could be negated to generate an error if a file or line does **not** match the given regex.
There could be a checkbox on the rule creation popup to enabled/disable the negation.

Example use case: Detect header files without include guards/pragma once

**Comment by jmecosta** [comment]
I suppose the include guards could be even a rule. We usually require this

**Comment by guwirth** [comment]
For me this sounds useful. I think is less effort.

**Comment by guwirth** [comment]
@j-ulrich please test #536

**Comment by j-ulrich** [comment]
It works! Thank you! :-)

However, I had to skip the unit tests because they were failing due to path issues with 8.3 path names (I don't have a Linux box around at the moment).

I used this RegEx to detect the include guards: `\s*#ifndef\s+(\w+)\s*\n#define\s+\1\s*\n[\w\W]+|[\w\W]*#pragma once[\w\W]+`
