### ISSUE TITLE
Default exceptions for MagicNumberCheck do not contain unsigned values

### ISSUE THREAD

**Issue by jens-auer** [wenns/sonar-cxx#542]
The default exceptions for MagicNumberCheck define 0 and 1 in integer and floating point formats, but not for unsigned integer values. The list  "0,1,0x0,0x00,.0,.1,0.0,1.0" should be extended to "0,1,0x0,0x00,.0,.1,0.0,1.0,0u,1u,0ul,1ul,1.0f, 0.0f,0LL,1LL,0ULL,1ULL".

**Comment by guwirth** [comment]
Makes sense. Nevertheless this setting is only the default. You can overwrite it.

**Comment by guwirth** [comment]
see #541
