### ISSUE TITLE
Add C++17 support

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#557]
@Bertk wrote: MSVC 14.0 (released date 20th July) has also some C++17 support and I think it will be very nice to have complete support for this compiler version with plug-in 1.0
(http://en.cppreference.com/w/cpp/compiler_support)

**Comment by guwirth** [comment]
@Bertk which C++17 extensions do you have in mind? Had a short look but found nothing changing the grammar?

**Comment by Bertk** [comment]
@guwirthYou are right this MSVC++ 14.0 brings C++17 library improvements and the grammar does not change. So we can postpone this activity until the next release of MSVC++ is available.

**Comment by guwirth** [comment]
There are no grammar changes currently. Close this issue.
