### ISSUE TITLE
Non-type template parameters

### ISSUE THREAD

**Issue by kocz** [wenns/sonar-cxx#573]
The following code creates parser errors :

```C++
/** n-sized array of type T */
template <size_t n, typename T>
struct TArray
{
  T t;
/**  --> */ TArray<n - 1, T> u;
};
```

**Comment by guwirth** [comment]
Which compiler are you using to develop the code?

**Comment by kocz** [comment]
g++ (GCC) 4.8.1

**Comment by kocz** [comment]
Additionally, to compile, you will need :
template <typename T>
struct TArray<0, T>
{
  T t;
};

**Comment by guwirth** [comment]
Problem can be reduced to:
```C++
TArray<n-1, T> u; // fails
S<n-1> s; // fails
S<10-1> s; // ok
```

**Comment by guwirth** [comment]
This seems to be the route cause. Maybe @ametselaar you have an idea how to fix it?

```Java
b.rule(templateArgument).is(
      b.firstOf(
        typeId,
        
        // FIXME: workaround to parse stuff like "carray<int, 10>"
        // actually, it should be covered by the next rule (constantExpression)
        // but it doesnt work because of ambiguity template syntax <--> relationalExpression
        shiftExpression,
        constantExpression,
        idExpression
      )
    );
```

**Comment by ametselaar** [comment]
I think I have the solution in my parse-gcc-extensions branch, but I failed to come up with the right git commands to produce a proper pull request.

**Comment by guwirth** [comment]
@ametselaar Tried to branch and rebase but there are too many conflicts. Which commit number contains the fix?
