### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by Kudret** [wenns/sonar-cxx#579]
Hi, does sonar-cxx have a check for dead code? 

Thank you

**Comment by jmecosta** [comment]
Nop but cppcheck does check somethings

**Comment by guwirth** [comment]
Philosophy of the plugin is to use external tools and read and display the resulting reports only.

**Comment by Kudret** [comment]
Oh, I see so it does not have a rule of its own but it can still do dead code checks via cppcheck.

Thanks
