### ISSUE TITLE
Overriding sonar.cxx.includeDirectories

### ISSUE THREAD

**Issue by KevinArturia** [wenns/sonar-cxx#585]
I have set my system includes in the Sonarqube GUI and would like to add other includes in the project level.

Is it possible to redefine the parameter without loosing the original includes?

**Comment by jmecosta** [comment]
Is it loosing the includes ?

**Comment by KevinArturia** [comment]
Yes, If I set `sonar.cxx.includeDirectories` in my `sonar-project.properties`, it loses the includes I defined in Sonarqube GUI.
I tried to do a bash like assignment:
    
    sonar-project.properties = $sonar-project.properties, includes

But this does not work either.

**Comment by jmecosta** [comment]
I think this a feature from core. Is it possible you can try with other
plugins?

**Comment by KevinArturia** [comment]
I haven't any other plugin to try with.
If this is a core feature I could ask the question on stackoverflow and see what the sonarsources guys say.

**Comment by jmecosta** [comment]
Yep that makes sense

**Comment by KevinArturia** [comment]
[Done](http://stackoverflow.com/questions/31564810/redefine-sonar-cxx-includedirectories-without-overriding-it)

**Comment by guwirth** [comment]
I'm closing this issue. Please re-open if still a problem.
