### ISSUE TITLE
Analyze C

### ISSUE THREAD

**Issue by ttoleung** [wenns/sonar-cxx#604]
Some of the code are still running on C and I want to run analysis on them and display into Sonar, how do I configure 0.9.3 so that I can run analysis on it? (currently running cppcheck and valgrind only), any   example property file I can look at?

**Comment by guwirth** [comment]
Same settings as for C++ code. Additional you should add .c to ```sonar.cxx.suffixes.sources``` and ```sonar.cxx.cFilesPatterns```. Setting ```sonar.cxx.cFilesPatterns``` will handle some C++ keywords as identifier.
