### ISSUE TITLE
Complexity of a function

### ISSUE THREAD

**Issue by schiean** [wenns/sonar-cxx#608]
Hi,

I was looking at FunctionComplexityCheckTest which asserts the complexity of certain cpp code.
However the score for this code is 8:

```C++
int func3(int a, int b) {        // +1
   if( a ) {                            // +1                                  2
      if( b ) {                         // +1                                  3
         return a+b ? 1 : 2;   // +1(return)  +1 (short if)   5 
      } else {
         return a+b ? 3 : 4;   // +1  +1                             7 
      }
   } else {
      if( b ) {                       // +1                                   8
         return a+b ? 5 : 6;  // +1  +1                             10
      } else {
         return a+b ? 7 : 8;  // +1  +1                              12
      }
   }
}
```

on this page http://docs.sonarqube.org/display/SONAR/Metrics+-+Complexity
we see how the complexity can be calculated.
In java the above example scores 12 (after making the ints into booleans because java does not allow if(int))

In CXX this scores 8.
Is there a reason for this ?

**Comment by guwirth** [comment]
**Commercial C++ plugin:** http://docs.sonarqube.org/display/SONAR/Metrics+-+Complexity:
The complexity gets incremented by one for: function definitions, **while** , **do while**, **for**, **throw** statements, **return** (except if it is the last statement of a function), **switch**, **case**, **default**, **&&** operator, **||** operator, **?** ternary operator, **catch**, **break**, **continue**, **goto**.

In **Community C++ plugin** it is currently (https://github.com/wenns/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/CxxAstScanner.java):
```Java
AstNodeType[] complexityAstNodeType = new AstNodeType[] {
// Entry points
CxxGrammarImpl.functionDefinition,
CxxKeyword.IF,
CxxKeyword.FOR,
CxxKeyword.WHILE,
CxxKeyword.CATCH,
CxxKeyword.CASE,
CxxKeyword.DEFAULT,
CxxPunctuator.AND,
CxxPunctuator.OR,
CxxPunctuator.QUEST
};
```

Means:

```C++
int func3(int a, int b) {       // +1:1
   if( a ) {                    // +1:2                               
      if( b ) {                 // +1:3                               
         return a+b ? 1 : 2;    // +1:4
      } else {
         return a+b ? 3 : 4;    // +1:5
      }
   } else {
      if( b ) {                 // +1:6                        
         return a+b ? 5 : 6;    // +1:7
      } else {
         return a+b ? 7 : 8;    // +1:8
      }
   }
}
```

**Comment by schiean** [comment]
I'm sorry, my question was more focused on the 'why'. 
By doing some code research I did notice how it is calculated in CXX, but my question is:
- 'Why does CXX not follow the Sonar-C++/Java convention, as it seems 11 or 12 would be the more correct score' ?
- Is it a Bug or a Feature ?

**Comment by guwirth** [comment]
To bei honest don't know why it is different. Goggling a little bit the cxx version seems to be more common. Don't understand why return should be counted?

**Comment by schiean** [comment]
There are lots of definitions for complexity and I doubt one of them has the authority to 'rule them all'.
However most of them focus on the idea that complexity is in relation with the amount of flows through a particular piece of code (or the number of testcases to cover all branches). This means that each exit  point leads to a new flow and accordingly should be part of the complexity.

I would vote that, for consistency with other plugins of sonarqube, the return statements should be counted for in the complexity. This way it is easier to reason about for programmers.

**Comment by guwirth** [comment]
I will do some tests with other tools next week (e.g. QAC++) and provide the results here. Final question is then: Doing it like other C++ tools or doing it like Sonar?

Do others have an opinion to this?

**Comment by guwirth** [comment]
Testing with QACPP 3.2.2: STCYC=4

**Comment by guwirth** [comment]
Testing with ccm v 1.1.7: Complexity=4

**Comment by guwirth** [comment]
I'm closing this issue. Please re-open if still a problem.
