### ISSUE TITLE
How are the sensors initialized?

### ISSUE THREAD

**Issue by richcat1982** [wenns/sonar-cxx#609]
Actually, this is not a issue but a question.
I'm now studying the plugin source code and I wonder how the sensors are intialized, take the CxxCppCheckSensor for an example:

  public CxxCppCheckSensor(ResourcePerspectives perspectives, Settings conf, ModuleFileSystem fs,
      RulesProfile profile) {
    super(perspectives, conf, fs, CxxMetrics.CPPCHECK);
    this.profile = profile;

    parsers.add(new CppcheckParserV2(this));
    parsers.add(new CppcheckParserV1(this));
  }

Where is the instance created and how is the parameter 'profile' passed into the instance?

Thanks a lot!

**Comment by jmecosta** [comment]
It's injected by the platform when a analysis is run. the core does all
that and the plugin does not contain any instatiation code. You might get
more insight in core document if any exist.

**Comment by richcat1982** [comment]
Hi，Jmecosta
Thanks for your reply ^_^
But what makes me confused is that the last parameter of the CxxCppCheckSensor constructor (the RulesProfile) is newly added by the CxxCppCheckSensor class itself, we can not find it from its parent.
Then how can the platform prepare a proper RulesProfile and feed the CxxCppCheckSensor constructor.
If you have any idea, please share it to me.
Thanks so much ^_^

**Comment by jmecosta** [comment]
What parent?

**Comment by jmecosta** [comment]
If you are talking the report sensor class that the constructors in there
are not called by the core its the cppcheck sensor class that is called.
How the profile is passed I don't know exactly since I haven't looked into
what injection library they use

**Comment by richcat1982** [comment]
I mean CxxCppCheckSensor extends CxxReportSensor
            CxxReportSensor implements Sensor
But the parameters of the constructor are quite different 
Oh, I guess I know the reason, I find this comment in the BatchComponent interface, which 
/**
 * Dependency Injection : all the classes implementing this interface are available in the batch IoC container.
 * Just add a parameter to the constructor of your component.
 *
 * @since 2.2
 */
Maybe I should check the related codes of the platform.

Thanks a lot ^_^

**Comment by richcat1982** [comment]
Hi，Jmecosta
Thank you so much for your patient reply
I know where and how I should check it.

Thanks^_^
