### ISSUE TITLE
squid parsing include files

### ISSUE THREAD

**Issue by tcooperma** [wenns/sonar-cxx#610]
I am trying to get sonar-cxx working and I changed sonar.cxx.includeDirectories to be "source,/path/to/gcc474/include/c++/4.7.4 and it is failing to parse the include files correctly.  Specifically it is finding string and then complains it cannot find include for '#include <bits/c++config.h>' along with a lot of others.  I am doing coming with in my configuration I am sure. help?  Is there email I can send to someone? I am todd.cooper@ll.mit.edu

**Comment by Bertk** [comment]
Did you check the Wiki and the sample project?
https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/samples/SampleProject2/sonar-project.properties

It would be helpful to get some information on the platform details as well. You should use "-X" option for sonar_runner to see the debug output from the plug-in.

**Comment by tcooperma** [comment]
I did check the wiki.
I will check the sample project.
I also think I need to add cppcheck?

**Comment by guwirth** [comment]
* for first steps see: https://github.com/wenns/sonar-cxx/wiki/Running-the-analysis
* cppcheck: https://github.com/wenns/sonar-cxx/wiki/Code-checkers (you have to execute it and forward the resulting report to cxx plugin)
* typical problem: https://github.com/wenns/sonar-cxx/wiki/Path-and-path-separator-issues
* How to get debug information: https://github.com/wenns/sonar-cxx/wiki/Get-debug-information

**Comment by guwirth** [comment]
I'm closing this issue. Please re-open if still a problem.
