### ISSUE TITLE
Some function definition can't be parsed.

### ISSUE THREAD

**Issue by bloodlee** [wenns/sonar-cxx#614]
A very strange issue.
These functions look common, such as:
1. void Rotator::setRotation(double rotation)
2. static unsigned deflate(vector* out, size_t* size, Hash* hash, ...

I got errors: "Unable to parse file: ...".

This is a C++ project. 
I tried on Sonarqube 4.5.5 and 5.1.2, and I got the same errors.

Do I need more configuration?
Thanks

**Comment by Bertk** [comment]
Please use sslr-cxx-toolkit-0.9.4-RC3.jar to identify the parsing issue. Typically the parser cannot parser the source of the function body because of missing declarations. The UI can be used to eliminate source code lines until the parser can build the AST tree (see also #476).
Good luck.

**Comment by bloodlee** [comment]
Thanks Bertk.
As you said, I tried as you suggested and there are some headers not found.
I will set the include path correctly and redo the parsing.
