### ISSUE TITLE
Tech debt is not calculated

### ISSUE THREAD

**Issue by vanomashey** [wenns/sonar-cxx#615]
Dear developers, 

I have installed the plugin and cppcheck. Analisys runs fine but tech debt is not calculated for the none of the projects. Also sample one. Please advice if it should be like this.

Regards,
Ivan

**Comment by guwirth** [comment]
Technical debt should be displayed:
* which SQ version are you using?
* which plugin version are you using?
* are there issues displayed?

Check also the wiki: https://github.com/wenns/sonar-cxx/wiki/Path-and-path-separator-issues

**Comment by guwirth** [comment]
Maybe this helps:
https://github.com/wenns/sonar-cxx/wiki/Code-checkers
https://github.com/wenns/sonar-cxx/wiki/Running-the-analysis
https://github.com/wenns/sonar-cxx/wiki/Path-and-path-separator-issues

Still problems? Try to get debug information:
https://github.com/wenns/sonar-cxx/wiki/Get-debug-information

**Comment by guwirth** [comment]
I'm closing this issue. Please re-open if still a problem.
