### ISSUE TITLE
ERROR - path normalizing of...

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#618]
After analyzing a project I get:

```
15:26:18.063 INFO  - Sensor CxxExternalRulesSensor
15:26:18.063 DEBUG - Using pattern 'reports\cxx-*.xml' to find reports
15:26:18.066 INFO  - Processing report 'D:\xxx\yyy\reports\cxx-report.xml'
15:26:18.066 INFO  - Parsing 'other' format
15:26:18.087 ERROR - path normalizing of 'D:\xxx\yyy\.\c:\GlobalMembers' failed: 'java.io.IOException: The filename, directory name, or volume label syntax is incorrect'
```
Using SQ 5.1.1 and v0.9.4-RC3.

**Comment by jmecosta** [comment]
That should be the same for every sensor? Is the issue reporting a
directory in the XML file?

**Comment by guwirth** [comment]
Problem is in normalizePathFull in https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/utils/CxxUtils.java. In case filename does not exist and is an absolute path the else path fails.

**Comment by guwirth** [comment]
Should be isAbsolute instead of exists?

**Comment by Bertk** [comment]
Yes, we should use more Java 7 methods and replace this Strings class with Path class. I also feel we should remove dependency to org.apache.commons.io.FilenameUtils in CxxReportSensor.java and use java.nio.file.path.
https://docs.oracle.com/javase/tutorial/essential/io/pathOps.html
https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html
