### ISSUE TITLE
VC2015 Compiler Warning Support

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#622]
Add new VC2015 compiler messages to https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/resources/compiler-vc.xml

**Comment by guwirth** [comment]
@Bertk how did you extract the messages last time?

**Comment by Bertk** [comment]
@guwirth I reviewed the MSDN documentation and checked the VC++ blog. This was all manual effort. By the way, I missed this update: http://blogs.msdn.com/b/vcblog/archive/2015/06/22/format-specifiers-checking.aspx

**Comment by guwirth** [comment]
@Bertk What should be already in the file and what should be checked again?

**C/C++ Build Errors**
https://msdn.microsoft.com/en-us/library/8x5x43k7.aspx

**Code Analysis for C/C++ Warnings**
https://msdn.microsoft.com/en-us/library/a5b9aa09.aspx

**Comment by guwirth** [comment]
Comparing it found these which are missing:
```
C4121
C4473
C4474
C4475
C4476
C4477
C4478
C4774
C4775
C4776
C4777
C4778
```

**Comment by Bertk** [comment]
@guwirth Thanks for the review.
