### ISSUE TITLE
Could not get Visual Compiler to work

### ISSUE THREAD

**Issue by stephanerenou** [wenns/sonar-cxx#628]
Thanks for the great work on the product,
I wanted to benefit from your changes to reduce the configuration needed on my projects.

Based on https://github.com/wenns/sonar-cxx/wiki/Compilers I tried to set up my env to use the output of the compiler for both processing the errors and discovering the configuration.

I am running sonarQube 4.5.5 and C++ Community 0.9.3
I was able to create those parameters:
sonar.cxx.compiler.reportPath=./buildlog.log
sonar.cxx.compiler.parser=Visual C++
sonar.cxx.compiler.charset=UTF-8
sonar.cxx.compiler.regex=^(?<filename>.*)\((?<line>[0-9]+)\): warning (?<id>C\d\d\d\d):(?<message>.*)$

By the way, the compiler regex was not correct initially, and the only error I was getting was: The system cannot find the file specified. 
which made it hard for me to identify that my regex was not correct.

So my build does not import any of the errors reported by the compiler, even if those appear in my quality profile. I do not get any of the Cxxxx errors reported, while they are present in my log file.
Would there be any way for me to debug why an error does not get processed?
The only log that I get is:
15:45:39 17:45:39.119 INFO  - Sensor CxxCompilerSensor...
15:45:39 17:45:39.120 INFO  - Processing report 'C:\jenkins\workspace\Atlas3CCLC++Test\Atlas\ClientCommunicationLayer\CPP\src\Atlas3CCL\buildlog.log'
15:45:39 17:45:39.120 INFO  - Scanner 'Visual C++' initialized with report 'C:\jenkins\workspace\Atlas3CCLC++Test\Atlas\ClientCommunicationLayer\CPP\src\Atlas3CCL\buildlog.log', CharSet= 'UTF-8'
15:45:39 17:45:39.120 INFO  - Parsing 'Visual C++' format
15:45:39 17:45:39.187 INFO  - C++ compiler Warnings processed = 0
15:45:39 17:45:39.187 INFO  - Sensor CxxCompilerSensor done: 68 ms

How can I figure out why it did not get any of the errors?

Also, I was hoping to see all my include warning to disappear, but I still see things like:
16:13:00 18:12:59.964 WARN  - [C:\MYFILE.H]: cannot find the sources for '#include <pthread.h>'

Would there be any way to know what was extracted as configuration settings?

**Comment by jmecosta** [comment]
Try to run with debug information -X or/and -e
For the includes if you build with /v:diag you should see them being
included during the analysis in the start of the log

**Comment by stephanerenou** [comment]
Thanks for the hint, that help me getting further with the analysis.
I am still facing some issues as I get some “cannot find the sources” for some of my include.
This seems to be related to some errors that are displayed as:
Cannot extract information from current element: (TaskId:28) : Illegal char <:> at index 94: C:\jenkins\workspace\MYFULLCORRECTPATH\(TaskId:28)

Unfortunately I could not see what in my file was wrong and especially the line being processed?

And I can’t see those folders added to lines like: storing include root: xxx
-----------------------------------------------------------------------------------------------------------------------------------

**Comment by jmecosta** [comment]
Can you share your log file?

**Comment by stephanerenou** [comment]
Unfortunately not to a mailing list, but I could extract some of it. Unfortunately I don’t know which region to share?

-----------------------------------------------------------------------------------------------------------------------------------

**Comment by jmecosta** [comment]
The build log might not be supported, the minimum version is vs 2010. That
might be the reason of the warnings. We would need to see some of the
cl.exe calls to see how they look. In your case your probably best approach
is not use the cxx.compiler and just use the normal include parameters.

**Comment by stephanerenou** [comment]
Here I am building using VS2010 so this is why I was hoping to benefit from that great change that you did. I will continue to search to try to understand why those get thrown on my own.

Thanks for the support. I was thinking that it may be interesting to get those lines:
DEBUG - storing include root: xxxx
with a different log level as those could be quite usefull when reviewing a project, especially as starting sonarqube via Jenkins is complex to start in debug mode and knowing the include files is always interesting.

-----------------------------------------------------------------------------------------------------------------------------------
Stéphane Renou, Technical Design Manager – +33 (0) 4 99 13 27 94 – stephane.renou@intercall.com<mailto:stephane.renou@intercall.com>

**Comment by jmecosta** [comment]
vs 2010 should be ok, look at https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/test/resources/org/sonar/plugins/cxx/reports-project/compiler-reports/VC-report.log you can use that to compare with your log.

**Comment by stephanerenou** [comment]
Thanks, I think I found the guilty line.
The output of the plugin is like:
Line 1: WARN  - Cannot extract information from current element: "..\..\..\..\..\common\xxxxxxx\yyyy.cpp" : Illegal char <"> at index 87: C:\MyWorkingDir\"..\..\..\..\..\common\xxxxxxxx\yyyy.cpp"

Line 2: WARN - the include root 'C:\MyWorkingDir\common\xxx' doesn't exist


The CL line contains:
Task "CL"
  c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\CL.exe /c /I.\..\..\..\..\..\AAAA  /I".\..\..\..\..\..\common\xxxxxx" /nologo /W3 /WX- /Od /Oy- /D WIN32 /D NDEBUG /D _WINDOWS /D (......) /Fo"Release\\" /Fd"Release\vc100.pdb" /Gd /TP /analyze- /errorReport:queue "..\..\..\..\..\common\xxxxxxx\yyyy.cpp" "..\..\..\..\..\common\xxxxxx\zzzz.cpp" "..\..\..\..\..\common\xxxxxx\ffffff.cpp"

Concerning line 1:
I guess this refers to : "..\..\..\..\..\common\xxxxxxx\yyyy.cpp"
It appears as if the last parts (the ones with yyyy.cpp) are added with the quote that makes the path to be unreadable. But I guess this is not a concern as the system is searching for a path here.

Concerning line 2:
I guess this refers to: /I".\..\..\..\..\..\common\xxxxxx" that is not processed correctly. That time, it seems as if the series of ..\.. are dropped from the path so the plugin searches for a location incorrect as just below working dir.

Compared to your example, it seems that my include path that are in quotes are relative while yours are absolute or without quotes.

I also guess there is no way for me to add some include files if the processor did not discover them correctly, either I use the includeDir or if not provided you would search the build log?

Lastly I also get

WARN  - the include root 'C:\Program Files(x86)\Microsoft Visual Studio 10.0\VC\include' doesn't exist
Looking at my system I can see that folder
-----------------------------------------------------------------------------------------------------------------------------------

**Comment by jmecosta** [comment]
few things you can try:

1. patch your log and remove the ", see if this helps
2. use sonar.cxx.includeDirectories to add directories, see https://github.com/wenns/sonar-cxx/blob/master/integration-tests/testdata/boosttest_project/sonar-project.properties

regarding the relative paths, can you provide a sample project that i can use to create a test?

**Comment by guwirth** [comment]
I'm closing this issue. Please re-open if still a problem.
