### ISSUE TITLE
sonar-cxx 0.9.2 doesn't show any issue with sonar 4.5.1

### ISSUE THREAD

**Issue by fasssl** [wenns/sonar-cxx#630]
Hello,

I have installed sonar-cxx 0.9.2 with sonar 4.5.1, when we run the analysis we found no issues. It is activated the sonar-way with 663 rules and 10 own rules.

When we run the analysis the properties are:
sonar.projectKey=proj
sonar.projectName=proj
sonar.projectVersion=1.0
sonar.language=c++
sonar.sources=.

can you help me? is very strange that the source code doesn't have any issue.

thanks in advance

**Comment by jmecosta** [comment]
Hi

Have you tried to check the wiki

**Comment by fasssl** [comment]
Thanks for the answer!

We are using visual studio 6, and compiling with msdev.
If i undertood well from the wiki is mandatary to have the log of the compilation and also the cppcheck (or similar tool described in the wiki) and both outputs are needed for this plugin, the plugin doesnt work alone.
Can you Tell me if this is correct ?

thanks in advance

**Comment by jmecosta** [comment]
The plugin has some built in rules however to improve the parser you must
provide accurate build information.  For cppcheck you should run the tool
outside.

You visual studio version seems really off to what we use currently by the
way. So the build log might not help for you

**Comment by fasssl** [comment]
Hi, thanks,
I have something wrong and I don't see where the problem is...
I put in my svn the project example: SAMPLE-test.cpp, etc...
then I have configure jenkins with only one step, the sonar check, in the directory where the files  *.cpp and  *,h are, with the following configuration:
sonar.projectName=test
sonar.projectVersion=1.0
sonar.projectKey=test
sonar.sources=.

And sonar is returning 0 issues.

Do you know where the problem should be?

thanks in advance!

**Comment by jmecosta** [comment]
have you enable any rules for the repository c++ SonarQube? 

![image](https://cloud.githubusercontent.com/assets/1041352/9981314/abe00b00-5fc2-11e5-8713-bf58da74bcc0.png)

try to update also your plugin: https://github.com/wenns/sonar-cxx/releases/download/cxx-0.9.4-RC3/sonar-cxx-plugin-0.9.4-RC3.jar

**Comment by fasssl** [comment]
yes are active
![imagen_2](https://cloud.githubusercontent.com/assets/14232621/9981423/e70a476e-5fbc-11e5-898a-568561b55d4c.jpg)
![imagen_1](https://cloud.githubusercontent.com/assets/14232621/9981424/e70e53ae-5fbc-11e5-9b5f-395975ee7d15.jpg)

**Comment by jmecosta** [comment]
no they are not, you have cppcheck,  rats vera and valgrind. all of those require you to run the external tools before the analysis. 

the ones you can try is the repository SonarQube c++, try upgrading also to the one i mention

**Comment by fasssl** [comment]
ok, thanks I will upgrade the plugin.

**Comment by jmecosta** [comment]
And don't forget to enable the rules

**Comment by fasssl** [comment]
ok, I think that in my actual version are enable but I will do double check.

thanks a lot! I will say if it works

![imagen_1](https://cloud.githubusercontent.com/assets/14232621/9981472/740b3294-5fbe-11e5-999f-772ff130f469.jpg)
![imagen_2](https://cloud.githubusercontent.com/assets/14232621/9981473/77aaef5c-5fbe-11e5-95a5-a92678a210ad.jpg)

**Comment by fasssl** [comment]
I all, it works fine, thanks for your support

**Comment by OhLadyTam** [comment]
My rules are active but I still cannot see issues. And I use the latest version of cxx plugin. What can I do?

**Comment by guwirth** [comment]
@OhLadyTam this issue is already closed. Please create a new one.
