### ISSUE TITLE
add tags for CXX rules 

### ISSUE THREAD

**Issue by Bertk** [wenns/sonar-cxx#636]
SQ 4.x and 5.x can filter rules using tags. Currently CXX has only tags for some check.
I added tags for some CppCheck, RATS and PC-lint rules. Should I create a PR for this commit? https://github.com/wenns/sonar-cxx/commit/1fe38724d4eb38d998999e0c71805c179dcff38c

**Comment by guwirth** [comment]
Hi @Bert,  yes please provide a PR. Even though it is sometimes difficult to assign a rule to a specific tag. Same is with SQALE characteristics.

**Comment by Bertk** [comment]
PR created #637
