### ISSUE TITLE
Tech Debt is not calculated

### ISSUE THREAD

**Issue by Dipalee24** [wenns/sonar-cxx#638]
Dear developers,

I have installed the plugin and cppcheck. Analysys runs fine but tech debt is not calculated for the none of the projects. Also sample one. No Errors are visible in Sonar log. Please advice if it should be like this.
I am using sonarqube-5.1.2 version and sonar-runner-2.4 and sonar-cxx-plugin-0.9.3.jar

Regards,
Dipalee

**Comment by jmecosta** [comment]
Hi,

You need to run cppcheck outside the analysis, check the documentation its
very clear what you need to do to get that

**Comment by Dipalee24** [comment]
Hi  Jorge,

Didn't  get  what  you  want  to  convey  exactly.  I  have  already 
checked  the  documentation  and  used  Sonar  as  per 
https://github.com/wenns/sonar-cxx/wiki/Running-the-analysis

Not  getting , how to run cppcheck outside the analysis ?   I  have  done 
for  non-mavenised  project.

Can  you  share  more  details  ?


Thanks & Regards
Dipalee Devdatta Mahajan
Tata Consultancy Services Limited
Mailto: dipalee.gaikwad@tcs.com
Website: http://www.tcs.com
____________________________________________
Experience certainty.   IT Services
                        Business Solutions
                        Consulting
____________________________________________

**Comment by guwirth** [comment]
Maybe this helps:
https://github.com/wenns/sonar-cxx/wiki/Code-checkers
https://github.com/wenns/sonar-cxx/wiki/Running-the-analysis
https://github.com/wenns/sonar-cxx/wiki/Path-and-path-separator-issues

Still problem? Try to get debug information:
https://github.com/wenns/sonar-cxx/wiki/Get-debug-information

**Comment by guwirth** [comment]
I'm closing this issue. Please re-open if still a problem.

**Comment by Dipalee24** [comment]
Hi  ,

As  per  my  understanding  there  are  C++  rules  that  are  applied  on 
 the  code  by  Sonarcube  , pls  refer  attached  screen shot. 

Are  the  errors / warnings  reported  by  Sonar  itself  after  scanning 
code  against  these  rules . ? 






Thanks & Regards
Dipalee Devdatta Mahajan
Tata Consultancy Services Limited
Mailto: dipalee.gaikwad@tcs.com
Website: http://www.tcs.com
____________________________________________
Experience certainty.   IT Services
                        Business Solutions
                        Consulting
____________________________________________
