### ISSUE TITLE
Tech Debt is not calculated for C++ Sonar Plugin

### ISSUE THREAD

**Issue by Dipalee24** [wenns/sonar-cxx#639]
Dear developers,

I have installed the plugin and cppcheck. Analysis runs fine but tech debt is not calculated for the none of the projects. Also sample one. No Errors are visible in Sonar log. Please advice if it should be like this.
I am using sonarqube-5.1.2 version and sonar-runner-2.4 and sonar-cxx-plugin-0.9.3.jar
I  have  been  told  that  I need to run cppcheck outside the analysis,  but  as  per  my  understanding  there  are  C++  rules  that  are  applied  on  the  code  by  Sonarcube  , pls  refer  attached  screen shot.  
where Are  the  errors / warnings  reported  by  Sonar  itself  after  scanning  code  against  these  rules . ?  

Or only feeded  logs  by  cppcheck / compilers  will be used  by sonar for reporting,  if  it  is  the  case  what  is  purpose or advantage of using Sonarcube for C++  in  case  it  is  not  reporting  any  errors ?

![image 4a70b622ca2fc76a](https://cloud.githubusercontent.com/assets/13449961/10423633/0fe35b82-70e6-11e5-8547-ad3294a02cf1.jpg)

Regards,
 Dipalee

**Comment by jmecosta** [comment]
hi,

click the 663 rules, then clikc again the 663 rules. this will take you to the profile itself. be sure you have this:

![rules](https://cloud.githubusercontent.com/assets/1041352/10423818/9bd301f6-70d2-11e5-9fbb-dc80677d870f.png)

**Comment by Dipalee24** [comment]
I see following  on  my  PC...
![sonarcube_c _rules](https://cloud.githubusercontent.com/assets/13449961/10424044/700bf11a-70e9-11e5-8313-171d8ef559db.jpg)

But  then  why  it's  not  reporting  any  code  issues  as  per  C++ rules  set.  Why  it  needs  cppcheck  result /log  or  compiler  log  to  report  code  issues ?

**Comment by jmecosta** [comment]
click the Repository, as in my picture.

**Comment by Dipalee24** [comment]
yeah , I did,  please check  below screenshot,,  but why I can't see any Sonarcube C++ rules in my list  similar to you ?????
![sonarcube_c _rules_2](https://cloud.githubusercontent.com/assets/13449961/10427918/0e2f0f14-710b-11e5-8af3-1aa855850725.jpg)

**Comment by jmecosta** [comment]
Try enabling them... Check sonar doc to see how to work with sonar ui.

**Comment by Dipalee24** [comment]
If I login as  ADMIN  in  Sonar  then  I  see  following screenshot.  
![sonarcube_c _rules_3](https://cloud.githubusercontent.com/assets/13449961/10447515/9a964a98-71a2-11e5-8ea3-357601b13eee.jpg)

That means the C++ rules are enabled , but still errors are not getting reported.
can I get the reason please ?

**Comment by jmecosta** [comment]
please read the documentation,
http://docs.sonarqube.org/display/SONAR/Configuring+Rules this is a core
feature and has nothing to do with the plugin.

you must first understand how to configure quality profiles in order to use
plugins.

the documentation might not be updated to your version but it will teach
you what a quality profile is in sonar and hopefully you will find your way
on how to enable those rules in your quality profile
