### ISSUE TITLE
Support Valgrind Helgrind XML Report

### ISSUE THREAD

**Issue by curtpm** [wenns/sonar-cxx#640]
when running valgrind with the helgrind tool "valgrind --tool=helgrind" the final xml reports are not picked up.

```
Could not add the issue, details: 'The rule 'valgrind:Race' does not exist.'
```

Is there a way to add a CustomRule to get some kinda of basic reporting for these kind of errors?

**Comment by jmecosta** [comment]
Each sensor supports custom rules via template rule. You just need to find
it in the profile and create a new one with name, you can try that

**Comment by curtpm** [comment]
Thanks for the reply, i did setup a custom rule from the valgrind template for a "Race" type.
It works fine for basic support.

Is there any way to get the output better formatted? like the normal valgrind report it seems to condense the entire stack trace onto a single line and makes it very hard to read.

**Comment by jmecosta** [comment]
That I am ensure, can you try formating the messages before sonar? We also
have this problem in our Intel inspector report and I think the sonar ui
might just limited. I remember in old versions it was possible to provide
big messages for parse errors but its not the case anymore

**Comment by curtpm** [comment]
I know this issue is closed, but sonar 5.2 has support for an issue to reference multiple locations in a code base.   

This is exactly what helgrind data needs, the xml output is an array of locations where the data race was detected. Any plans on adding some kind of support for this? 

I also wouldn't mind trying to make an attempt to implement it, but i might need some guidance.

**Comment by jmecosta** [comment]
Can you point out where this feature is documented in 5.2.

**Comment by curtpm** [comment]
https://groups.google.com/forum/#!msg/sonarqube/ZCIsvd41Esk/tHZOUEXfDwAJ

````
- More features are available to better manage issues
        Support for more precise issue location and multiple location (<= this requires language plugins to provide the information)
````

**Comment by jmecosta** [comment]
i think this is what you are looking for: https://jira.sonarsource.com/browse/SONAR-4865
is the race issue occurring only on a single file, because if i understand correctly that's mandatory. if a stacktrace is to be saved then i dont think this will be supported

**Comment by curtpm** [comment]
OK, thanks for the reply.
