### ISSUE TITLE
Add SQ 5.2 to Travis build

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#648]
Add SQ 5.2 to Travis build:
https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.2-RC2.zip

See #649

**Comment by jmecosta** [comment]
Curious to see if this works. At least I was not able to run c++ analysis without the colorizer

**Comment by guwirth** [comment]
Also forceZeroCoverage seems no more to work?

**Comment by jmecosta** [comment]
Does that thing do some processing that access db? This is no longer
possible in plugin side. We need to update to 5.2 rc2 to see what
components are broken. Problem I can't find those artifacts anywhere

**Comment by guwirth** [comment]
Currently known issues:
* additional warning: WARN  - Unable to get a valid mac address, will use a dummy address
* Seems there is a problem to access the analysis log. This is different with SQ 5.2? Think SQ will create it on server side and provide it delayed? Blocker to use sonar runner in build automation. 
* Also forceZeroCoverage seems no more to work?

**Comment by guwirth** [comment]
> Does that thing do some processing that access db?

Code is here https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/coverage/CxxCoverageSensor.java. Maybe context.GetMeasure? How do I know which API is using the DB?

> We need to update to 5.2 rc2 to see what components are broken.

Depends. If there are breaking changes in SQ 5.2 we should first release a final 0.9.4. For my understanding plugin should work with SQ 4.5 to 5.2. 

> Problem I can't find those artifacts anywhere

What are you looking for?

**Comment by jmecosta** [comment]
On Sun, 18 Oct 2015 at 18:33 Günter Wirth <notifications@github.com> wrote:

> Does that thing do some processing that access db?
>
> Code is here
> https://github.com/wenns/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/coverage/CxxCoverageSensor.java.
> Maybe context.GetMeasure? How do I know which API is using the DB?
>
yep, it looks like its that: changes are here:
https://groups.google.com/forum/#!topic/sonarqube/ZCIsvd41Esk but unclear
to me what needs changing

> We need to update to 5.2 rc2 to see what components are broken.
>
> Depends. If there are breaking changes in SQ 5.2 we should first release a
> final 0.9.4. For my understanding plugin should work with SQ 4.5 to 5.2.
>
is not 0.9.3 already supporting 5.1.2? or is there something really
important in 0.9.4-SNAPSHOT. if we release 0.9.4 only supporting 5.1.2 then
there will be a big period where we dont have a version compatible with
5.2. or you need to provide two releases really close to each other.

> Problem I can't find those artifacts anywhere
>
> What are you looking for?
>
was trying to follow these:
https://groups.google.com/forum/#!topic/sonarqube/sJLMsMUxo5A, so bump the
api to 5.2-RC2 but build fails

**Comment by guwirth** [comment]
> is not 0.9.3 already supporting 5.1.2?

Because there are 121 changes since v0.9.3: https://github.com/wenns/sonar-cxx/issues?q=milestone%3A%22M+0.9.4%22+is%3Aclosed. Make them only for 5.2 users available makes less sense. 5.2 is also a big change of SQ. Fear it needs a little bit longer to be able to use it really productive.

**Comment by jmecosta** [comment]
, let's release it. It's been in RC 3 for long enough
