### ISSUE TITLE
runner is not listing the CxxCppCheckSensor while runner is started

### ISSUE THREAD

**Issue by dinesh25** [wenns/sonar-cxx#653]
Hi,
I am new to sonar, i have installed sonarqube on RHEL machine and its version is 5.1.1.
and the runner's version is 2.4.
I have four cpp related plugins, i tried with each one,

sonar-cxx-plugin-0.9.4-RC3.jar
sslr-cxx-toolkit-0.9.4-RC3.jar
sonar-cpp-plugin-3.6.jar
sonar-cpp-plugin-3.5.jar
sonar-cxx-plugin-0.9.jar

nothing seems to be listing the Sensor CxxCppCheckSensor . i need this for integrating cppcheck with the sonar. my cppcheck version is 1.68. 
i have included sonar.cfamily.cppcheck.reportPath = <path of my cppchecks xml file> in my sonar.project.properties file too. 

Am I doing something wrong here ? Please help me out. 

1.And do these cpp plugins needs license or trial key for proceeding? 
2. Can cppcheck's xml report alone<not involving other src code analysis> be viewed in sonar's dashboard? 

Thanks in advance :)

**Comment by jmecosta** [comment]
Hi

Try to have the 0.9.4 rc4 now and only that in the extensions plugins folder. Then go through our wiki and read it to get a feeling how things work.

Regarding the cpp plugin you have is relevant to to the paid sonarsource plugin so you can enquire them directly

**Comment by dinesh25** [comment]
Hi, thank you very much for responding me back,
as you said i loaded only sonar-cxx-plugin-0.9.4-RC3.jar to plugins folder and tried it, still i see the same log, seems like CxxCppCheckSensor has not invoked yet.

entries after invoking sonar-runner:
11:50:49.373 INFO  - Source paths: .
11:50:49.373 INFO  - Source encoding: UTF-8, default locale: en_US
11:50:49.374 INFO  - Index files
11:50:49.381 INFO  - 0 files indexed
11:50:49.410 INFO  - Sensor Lines Sensor
11:50:49.411 INFO  - Sensor Lines Sensor (done) | time=1ms
11:50:49.411 INFO  - Sensor QProfileSensor
11:50:49.424 INFO  - Sensor QProfileSensor (done) | time=13ms
11:50:49.424 INFO  - Sensor InitialOpenIssuesSensor
11:50:49.435 INFO  - Sensor InitialOpenIssuesSensor (done) | time=11ms
11:50:49.435 INFO  - Sensor ProjectLinksSensor
11:50:49.442 INFO  - Sensor ProjectLinksSensor (done) | time=7ms
11:50:49.442 INFO  - Sensor VersionEventsSensor
11:50:49.457 INFO  - Sensor VersionEventsSensor (done) | time=15ms
11:50:49.457 INFO  - Sensor SCM Sensor
11:50:49.457 INFO  - No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
11:50:49.457 INFO  - Sensor SCM Sensor (done) | time=0ms
11:50:49.457 INFO  - Sensor CPD Sensor
11:50:49.457 INFO  - Sensor CPD Sensor (done) | time=0ms
11:50:49.509 INFO  - Loaded quality gate 'SonarQube way'
11:50:49.565 INFO  - Compare to previous analysis (2015-10-21)
11:50:49.572 INFO  - Compare over 30 days (2015-09-21, analysis of Fri Oct 09 17:40:31 IST 2015)
11:50:50.101 INFO  - Execute decorators...
11:50:50.239 INFO  - Store results in database

execution is sucessful.

even got a confusion and tried with sslr-cxx-toolkit-0.9.4-RC3.jar alone in plugins folder and tried too, the same error. 

And my sonar-project.properties is as below:
# must be unique in a given SonarQube instance
sonar.projectKey=sample:project
# this is the name displayed in the SonarQube UI
sonar.projectName=SampleTest
sonar.projectVersion=1.0
#sonar.language=cpp

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# Since SonarQube 4.2, this property is optional if sonar.modules is set.
# If not set, SonarQube starts looking for source code from the directory containing
# the sonar-project.properties file.
#sonar.projectBaseDir=

sonar.cfamily.cppcheck.reportPath=cppcheck-report.xml
sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sources directory only contains cppcheck-report.xml, no other files. 
and my sonar-runner command is :
 /opt/sonar-runner-2.4/bin/sonar-runner -Dproject.settings=sonar-project.properties

guide me to proceed further. 

Thank you :)

**Comment by jmecosta** [comment]
thats good, now you need to read a bit of the documentation and you will
get it ;) see https://github.com/wenns/sonar-cxx/wiki/Running-the-analysis its
the first sentence in the page.

**Comment by kingwings** [comment]
I have same problem after I upgrade to SONAR5.2 from 5.1.1 with sonar-cxx-plugin-0.9.4.jar. I checked the SonarQube compatibility matrix, found it is partial supported. Is there any workaround solution, I don't want to downgrade our SONAR. Following is the log snippet:

[INFO] Sensor CxxSquidSensor (done) | time=184918ms
[INFO] Sensor CxxCoverageSensor
[INFO] Sensor CxxCoverageSensor (done) | time=391ms
[INFO] Sensor SCM Sensor
[INFO] No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
[INFO] Sensor SCM Sensor (done) | time=0ms
[INFO] Sensor Code Colorizer Sensor
[INFO] Sensor Code Colorizer Sensor (done) | time=15110ms
[INFO] Sensor CPD Sensor
[INFO] DefaultCpdEngine is used for c++

**Comment by jmecosta** [comment]
Nop you will need to wait for 5.3. There is a rc 2 already so it wont be
long

**Comment by guwirth** [comment]
Cxx plugin is not tested with SQ5.2+ currently.  So we are also interested in your feedback and experience. 

To use scm you should add something like to your configuration:

  sonar.scm.enabled=true
sonar.scm.url=scm:git:git@github.com:wenns/sonar-cxx.git

You also can try to add more logging to get more information: 
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

**Comment by kingwings** [comment]
No, we don't use scm. And before upgrade, I am using sonar-cxx-plugin-0.9.4-RC1.jar + SONAR5.1.1, and Then I tried sonar-cxx-plugin-0.9.4-RC1.jar + SONAR5.2 and met the following problem:

[ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.7.1:sonar (default-cli) on project ProAgent: Unable to highlight file [moduleKey=com.wn.pce.rbss.perf.pcesb:ProAgent, relative=develop/Agents/Common/cvssop/sources/pvversion.h, basedir=C:\Jenkins\jobs\ProAgent\workspace] from offset 14975 to offset 14996: 14996 is not a valid offset for file [moduleKey=com.wn.pce.rbss.perf.pcesb:ProAgent, relative=develop/Agents/Common/cvssop/sources/pvversion.h, basedir=C:\Jenkins\jobs\ProAgent\workspace]. Max offset is 14995 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.7.1:sonar (default-cli) on project ProAgent: Unable to highlight file [moduleKey=com.wn.pce.rbss.perf.pcesb:ProAgent, relative=develop/Agents/Common/cvssop/sources/pvversion.h, basedir=C:\Jenkins\jobs\ProAgent\workspace] from offset 14975 to offset 14996
......

So finally I tried SONAR5.2 and sonar-cxx-plugin-0.9.4.

**Comment by jmecosta** [comment]
for reference you are hitting this bug in the platform: https://jira.sonarsource.com/browse/SONAR-7008

the only way is to apply the patch that it was used to fixedd 5.3 on top of 5.2. or you need to wait for 5.3

**Comment by kingwings** [comment]
@guwirth do you mean this issue won't fix on SONAR5.2 or sonar-cxx-plugin won't test and support on SONAR5.2? If so, is sonar-cxx-plugin testing on SONAR5.3?
