### ISSUE TITLE
We cannot find the  'Sonar \ C++ skip parser error' rule

### ISSUE THREAD

**Issue by jesuissur** [wenns/sonar-cxx#654]
Hi there

The Error Recovery page (https://github.com/wenns/sonar-cxx/wiki/Error-Recovery) states that we could turn on the rule  'Sonar \ C++ skip parser error', but we cannot find this rule.
Are we looking at the wrong place?  We're using Sonar 5.1.2 with cxx plugin version v0.9.4-RC4.

Thanks
Phil

**Comment by jmecosta** [comment]
hi,

i have it here:

![2015-10-20 20_45_20-store](https://cloud.githubusercontent.com/assets/1041352/10615995/8a265008-776b-11e5-8ff1-e845ac8ba9dd.png)

**Comment by jesuissur** [comment]
Ooooh, my bad.  My current Quality Profile was selected as a filter hence the "missing" rule.
Thanks
